// Kratki pregledi cjelina — prozor koji se otvori klikom na cjelinu u izborniku Lessons.
// Uređuje se ručno (ne generira ga osvjezi.js).
//   h  = naslov (stranica 1)
//   s  = jedna kratka rečenica ispod naslova (nije obavezno)
//   ex = 1–2 primjera [hrvatski, engleski] (stranica 1, nije obavezno)
//   p2 = stranica 2, popis blokova:
//        { t: [[hr, en], ...] }       tablica: hrvatski lijevo, prijevod desno
//        { g: [[zaglavlje...], [redak...], ...] }  mala mreža, prvi redak je zaglavlje
//              (gh: [0, 2] = koji su retci zaglavlja, ako ih je više)
//        { w: [[hr, en], ...] }       riječi u jednom retku
// Broj koraka, prag i trajanje testa prozor čita iz data.js.
window.PREGLEDI = {
  // ---------- 1 ----------
  'Lesson 1': { h: 'Tus primeras oraciones en croata',
    ex: [['Kava je dobra.', 'El café está bueno.'], ['More je plavo.', 'El mar es azul.']],
    p2: [{ t: [['Grad je velik.', 'La ciudad es grande.'], ['Kuća je velika.', 'La casa es grande.'], ['More je veliko.', 'El mar es grande.']] },
         { w: [['kuća', 'casa'], ['grad', 'ciudad'], ['more', 'mar'], ['kava', 'café']] }] },
  'Vocabulary 1': { h: 'Cosas, colores y tamaños', s: 'Unas 40 palabras cotidianas.',
    p2: [{ w: [['soba', 'habitación'], ['stol', 'mesa'], ['knjiga', 'libro']] },
         { w: [['crven', 'rojo'], ['plav', 'azul'], ['žut', 'amarillo']] },
         { w: [['velik', 'grande'], ['mali', 'pequeño'], ['nov', 'nuevo']] }] },
  'Grammar 1': { h: 'Terminaciones que concuerdan',
    ex: [['Kuća je velika.', 'La casa es grande.'], ['Kava nije dobra.', "El café no está bueno."]],
    p2: [{ g: [['grad', 'kuća', 'more'], ['velik', 'velika', 'veliko']] },
         { w: [['je', 'es / está'], ['nije', "no es / no está"]] }] },
  'Practice 1': { h: 'Lee tus primeros textos', s: 'Una ciudad, una habitación y un café.',
    p2: [{ t: [['Kava, molim.', 'Un café, por favor.'], ['Izvolite.', 'Aquí tiene.'], ['Hvala!', '¡Gracias!']] }] },
  'Test 1': { h: 'Demuestra lo que sabes', s: 'Palabras, terminaciones y oraciones sencillas.',
    p2: [{ g: [['grad', 'kuća', 'more'], ['star', 'stara', 'staro']] },
         { w: [['je', 'es / está'], ['nije', "no es / no está"]] }] },

  // ---------- 2 ----------
  'Lesson 2': { h: 'Hablar de personas',
    ex: [['Ja sam studentica.', 'Soy estudiante.'], ['Ona je visoka.', 'Ella es alta.']],
    p2: [{ t: [['Ja sam Ana.', 'Soy Ana.'], ['Ti si Marko.', 'Eres Marko.'], ['Oni su veseli.', 'Son alegres.']] },
         { w: [['ja', 'yo'], ['ti', 'tú'], ['on', 'él'], ['ona', 'ella']] }] },
  'Vocabulary 2': { h: 'Profesiones, países y carácter', s: 'Palabras sobre personas y tus primeros saludos.',
    p2: [{ w: [['kuhar', 'cocinero'], ['vozač', 'chofer'], ['učitelj', 'maestro']] },
         { w: [['Hrvat', 'croata'], ['Talijan', 'italiano'], ['Nijemac', 'alemán']] },
         { t: [['Kako si?', '¿Cómo estás?'], ['Dobro sam.', "Estoy bien."]] }] },
  'Grammar 2': { h: 'El verbo “ser/estar”',
    ex: [['Mi smo turisti.', 'Somos turistas.'], ['Nisam gladan.', "No tengo hambre."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['sam', 'si', 'je'], ['mi', 'vi', 'oni'], ['smo', 'ste', 'su']], gh: [0, 2] }] },
  'Practice 2': { h: 'Conoce gente nueva', s: 'Presentaciones, un café y un equipo.',
    p2: [{ t: [['Tko si ti?', '¿Quién eres?'], ['Kako ste?', '¿Cómo está? / ¿Cómo están?'], ['Dobro sam, hvala.', "Estoy bien, gracias."]] }] },
  'Test 2': { h: 'Demuestra lo que sabes', s: 'Personas, “ser/estar” y presentaciones.',
    p2: [{ g: [['on', 'ona', 'oni'], ['visok', 'visoka', 'visoki']] },
         { w: [['sam', 'soy / estoy'], ['smo', 'somos / estamos'], ['su', 'son / están']] }] },

  // ---------- 3 ----------
  'Lesson 3': { h: 'Cosas que haces',
    ex: [['Pijem čaj.', "Tomo té."], ['Ana radi.', 'Ana trabaja.']],
    p2: [{ t: [['čitam', 'leo'], ['čitaš', 'lees'], ['čita', 'lee (él / ella)']] },
         { w: [['piti', 'beber'], ['jesti', 'comer'], ['raditi', 'trabajar'], ['spavati', 'dormir']] }] },
  'Vocabulary 3': { h: 'Verbos cotidianos', s: 'Verbos y las cosas que van con ellos.',
    p2: [{ w: [['čitati', 'leer'], ['pisati', 'escribir'], ['piti', 'beber']] },
         { w: [['kruh', 'pan'], ['sir', 'queso'], ['čaj', 'té']] },
         { w: [['uvijek', 'siempre'], ['često', 'a menudo'], ['nikad', 'nunca']] }] },
  'Grammar 3': { h: 'El presente',
    ex: [['Učim hrvatski.', "Aprendo croata."], ['Ne pijem sok.', "No tomo jugo."]],
    p2: [{ g: [['čitati', 'raditi', 'pisati'], ['čitam', 'radim', 'pišem'], ['čitaš', 'radiš', 'pišeš'], ['čita', 'radi', 'piše']] }] },
  'Practice 3': { h: 'Un día de acciones', s: 'Un departamento, una noche y un domingo tranquilo.',
    p2: [{ t: [['Što radiš?', '¿Qué haces?'], ['Učim hrvatski.', "Aprendo croata."], ['Gledam film.', "Veo una película."]] }] },
  'Test 3': { h: 'Demuestra lo que sabes', s: 'Verbos cotidianos en presente.',
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['pijem', 'piješ', 'pije']] },
         { w: [['ne pijem', "no tomo"]] }] },

  // ---------- 4 ----------
  'Lesson 4': { h: 'La familia',
    ex: [['Tata kuha, a brat uči.', 'Papá cocina y mi hermano estudia.'], ['Mama radi i čita.', 'Mamá trabaja y lee.']],
    p2: [{ t: [['i', 'y'], ['a', 'y, mientras que'], ['ali', 'pero']] },
         { w: [['mama', 'mamá'], ['tata', 'papá'], ['brat', 'hermano'], ['sestra', 'hermana']] }] },
  'Vocabulary 4': { h: 'Familia y hogar', s: 'Familia cercana, familia extendida y verbos nuevos.',
    p2: [{ w: [['mama', 'mamá'], ['tata', 'papá'], ['baka', 'abuela']] },
         { w: [['brat', 'hermano'], ['sestra', 'hermana'], ['dijete', 'niño']] },
         { w: [['imati', 'tener'], ['kuhati', 'cocinar'], ['živjeti', 'vivir']] }] },
  'Grammar 4': { h: 'Unir oraciones',
    ex: [['Mama radi i čita.', 'Mamá trabaja y lee.'], ['Ne plivam jer je hladno.', "No nado porque hace frío."]],
    p2: [{ t: [['i', 'y'], ['a', 'y, mientras que'], ['ali', 'pero'], ['jer', 'porque']] }] },
  'Practice 4': { h: 'La vida en familia', s: 'Una familia, una mañana ajetreada y un sábado en casa.',
    p2: [{ t: [['Ovo je obitelj.', 'Esta es una familia.'], ['Što radiš danas?', '¿Qué haces hoy?'], ['Baka kuha.', 'La abuela cocina.']] }] },
  'Test 4': { h: 'Demuestra lo que sabes', s: 'Palabras de familia, verbos y palabras para unir.',
    p2: [{ t: [['i', 'y'], ['a', 'y, mientras que'], ['ali', 'pero'], ['jer', 'porque']] }] },

  // ---------- 5 ----------
  'Lesson 5': { h: 'De compras',
    ex: [['Pijem kavu.', "Tomo café."], ['Trebate li vrećicu?', '¿Necesita una bolsa?']],
    p2: [{ t: [['Kava je dobra.', 'El café está bueno.'], ['Pijem kavu.', "Tomo café."], ['Jedem jabuku.', "Como una manzana."]] },
         { w: [['kruh', 'pan'], ['voda', 'agua'], ['sir', 'queso'], ['riba', 'pescado']] }] },
  'Vocabulary 5': { h: 'Compras y comida', s: 'Palabras del mercado y 10 verbos nuevos.',
    p2: [{ w: [['voda', 'agua'], ['juha', 'sopa'], ['riža', 'arroz']] },
         { w: [['kruh', 'pan'], ['mlijeko', 'leche'], ['meso', 'carne']] },
         { w: [['kupovati', 'comprar'], ['trebati', 'necesitar'], ['plaćati', 'pagar']] }] },
  'Grammar 5': { h: 'Tu primer caso',
    ex: [['Kupujem svježu salatu.', "Compro lechuga fresca."], ['Idem u trgovinu.', "Voy a la tienda."]],
    p2: [{ g: [['kava', 'crna kava'], ['Pijem kavu.', 'Pijem crnu kavu.']] },
         { w: [['u trgovinu', 'a la tienda'], ['na tržnicu', 'al mercado']] }] },
  'Practice 5': { h: 'En el mercado', s: 'Un mercado, una nota en el refrigerador y el desayuno.',
    p2: [{ t: [['Ana kupuje jabuku.', 'Ana compra una manzana.'], ['Trebamo kruh i rižu.', 'Necesitamos pan y arroz.'], ['Volim kavu!', '¡Me encanta el café!']] }] },
  'Test 5': { h: 'Demuestra lo que sabes', s: 'Comida, compras y tu primer caso.',
    p2: [{ g: [['kava', 'juha', 'salata'], ['kavu', 'juhu', 'salatu']] },
         { w: [['kruh', 'pan (sin cambio)']] }] },

  // ---------- 6 ----------
  'Lesson 6': { h: 'En la ciudad',
    ex: [['Vidim prijatelja.', 'Veo a un amigo.'], ['Čekam tramvaj.', "Espero el tranvía."]],
    p2: [{ t: [['Vidim prijatelja.', 'Veo a un amigo.'], ['Vidim tramvaj.', 'Veo un tranvía.'], ['Vidim psa.', 'Veo un perro.']] },
         { w: [['ulica', 'calle'], ['trg', 'plaza'], ['most', 'puente']] }] },
  'Vocabulary 6': { h: 'La ciudad y el tráfico', s: 'Personas, transporte y lugares de la ciudad.',
    p2: [{ w: [['tramvaj', 'tranvía'], ['vlak', 'tren'], ['bicikl', 'bicicleta']] },
         { w: [['ulica', 'calle'], ['trg', 'plaza'], ['most', 'puente']] },
         { w: [['vidjeti', 'ver'], ['čuti', 'oír'], ['voziti', 'manejar']] }] },
  'Grammar 6': { h: 'Personas y cosas',
    ex: [['Čekam prijatelja.', "Espero a un amigo."], ['Vidim ga.', 'Lo veo.']],
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['me', '='], ['te', 'te'], ['ga', 'lo'], ['je', 'la']] }] },
  'Practice 6': { h: 'La vida en la ciudad', s: 'Un viaje en tranvía, una calle con mucho movimiento y un perro perdido.',
    p2: [{ t: [['Ana čeka tramvaj.', 'Ana espera el tranvía.'], ['Tramvaj je pun.', 'El tranvía está lleno.'], ['Oprostite!', '¡Disculpe!']] }] },
  'Test 6': { h: 'Demuestra lo que sabes', s: 'La ciudad y todo el primer caso.',
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['ga', 'lo (a él, a eso)'], ['je', 'la']] }] },

  // ---------- 7 ----------
  'Lesson 7': { h: 'En la escuela: más de uno',
    ex: [['Knjige su nove.', 'Los libros son nuevos.'], ['Učenici pjevaju.', 'Los alumnos cantan.']],
    p2: [{ g: [['učenik', 'knjiga', 'pismo'], ['učenici', 'knjige', 'pisma']] },
         { w: [['škola', 'escuela'], ['olovka', 'lápiz'], ['ispit', 'examen']] }] },
  'Vocabulary 7': { h: 'Escuela y canciones', s: 'Palabras de la escuela, plurales y 10 verbos nuevos.',
    p2: [{ w: [['škola', 'escuela'], ['olovka', 'lápiz'], ['torba', 'bolsa']] },
         { w: [['ispit', 'examen'], ['ocjena', 'calificación'], ['zadaća', 'tarea']] },
         { w: [['pjevati', 'cantar'], ['igrati', 'jugar'], ['znati', 'saber']] }] },
  'Grammar 7': { h: 'El plural',
    ex: [['Stolovi su stari.', 'Las mesas son viejas.'], ['Djeca pjevaju.', 'Los niños cantan.']],
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['čitamo', 'čitate', 'čitaju']] }] },
  'Practice 7': { h: 'Días de escuela', s: 'Una escuela, un horario, un coro y alumnos nuevos.',
    p2: [{ t: [['Dobro jutro, djeco!', '¡Buenos días, niños!'], ['Djeca pjevaju.', 'Los niños cantan.'], ['Knjige su nove.', 'Los libros son nuevos.']] }] },
  'Test 7': { h: 'Demuestra lo que sabes', s: 'Sustantivos, adjetivos y verbos en plural.',
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['pjevamo', 'pjevate', 'pjevaju']] }] },

  // ---------- 8 ----------
  'Lesson 8': { h: 'Planes de verano',
    ex: [['Plivat ću.', 'Nadaré.'], ['Mi ćemo putovati.', 'Viajaremos.']],
    p2: [{ t: [['Plivat ću.', 'Nadaré.'], ['Putovat ćemo u subotu.', 'Viajaremos el sábado.'], ['Neću plivati.', "No nadaré."]] },
         { w: [['plaža', 'playa'], ['otok', 'isla'], ['sutra', 'mañana']] }] },
  'Vocabulary 8': { h: 'Planes y viajes', s: 'Vacaciones, días, ropa y 10 verbos nuevos.',
    p2: [{ w: [['plaža', 'playa'], ['otok', 'isla'], ['kofer', 'maleta']] },
         { w: [['sutra', 'mañana'], ['vikend', 'fin de semana'], ['tjedan', 'semana']] },
         { w: [['putovati', 'viajar'], ['plivati', 'nadar'], ['letjeti', 'volar']] }] },
  'Grammar 8': { h: 'El futuro',
    ex: [['Sutra ću plivati.', 'Mañana nadaré.'], ['Neću raditi.', "No trabajaré."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['ću', 'ćeš', 'će'], ['mi', 'vi', 'oni'], ['ćemo', 'ćete', 'će']], gh: [0, 2] }] },
  'Practice 8': { h: 'Planes y trayectos', s: 'Un plan de verano, una lista para la maleta y un boleto de tren.',
    p2: [{ t: [['Ići ćemo u Split.', 'Iremos a Split.'], ['Ustat ću rano.', 'Me levantaré temprano.'], ['Tata će voziti.', 'Papá manejará.']] }] },
  'Test 8': { h: 'Demuestra lo que sabes', s: 'Planes, viajes y el futuro.',
    p2: [{ t: [['Plivat ću.', 'Nadaré.'], ['Ja ću plivati.', 'Yo nadaré.'], ['Neću plivati.', "No nadaré."]] }] },

  // ---------- 9 ----------
  'Lesson 9': { h: 'Deporte y pasatiempos',
    ex: [['Moj hobi je fotografija.', 'Mi pasatiempo es la fotografía.'], ['Boli me koljeno.', 'Me duele la rodilla.']],
    p2: [{ t: [['moj dres', 'mi camiseta'], ['moja lopta', 'mi pelota'], ['moje koljeno', 'mi rodilla']] },
         { w: [['glava', 'cabeza'], ['ruka', 'brazo'], ['noga', 'pierna'], ['srce', 'corazón']] }] },
  'Vocabulary 9': { h: 'Deporte, cuerpo y “mi”', s: 'Palabras de deporte, el cuerpo y de quién es cada cosa.',
    p2: [{ w: [['klub', 'club'], ['trener', 'entrenador'], ['igrač', 'jugador']] },
         { w: [['glava', 'cabeza'], ['ruka', 'brazo'], ['noga', 'pierna']] },
         { w: [['moj', 'mi'], ['tvoj', 'tu'], ['naš', 'nuestro']] }] },
  'Grammar 9': { h: 'Mío, tuyo, nuestro',
    ex: [['njegova gitara', 'su guitarra (de él)'], ['Marko voli svoju sestru.', 'Marko quiere a su propia hermana.']],
    p2: [{ g: [['moj', 'moja', 'moje'], ['njegov', 'njegova', 'njegovo'], ['njezin', 'njezina', 'njezino']] },
         { w: [['svoj', 'mi / su (de él, de ella) propio'], ['čiji', 'de quién']] }] },
  'Practice 9': { h: 'Nuestro club, mi pasatiempo', s: 'Un pasatiempo, una pelota perdida y un club de fútbol.',
    p2: [{ t: [['Je li ovo tvoja lopta?', '¿Esta es tu pelota?'], ['Da, moja je!', "¡Sí, es mía!"], ['Naš klub je mali.', 'Nuestro club es pequeño.']] }] },
  'Test 9': { h: 'Demuestra lo que sabes', s: 'Posesivos, deporte y el cuerpo.',
    p2: [{ g: [['dres', 'lopta', 'koljeno'], ['moj', 'moja', 'moje']] },
         { w: [['svoj', 'mi / su (de él, de ella) propio']] }] },

  // ---------- 10 ----------
  'Lesson 10': { h: 'Ayer',
    ex: [['Gledao sam film.', 'Vi una película.'], ['Bilo je savršeno.', 'Fue perfecto.']],
    p2: [{ t: [['On je gledao.', 'Él vio.'], ['Ona je gledala.', 'Ella vio.'], ['Oni su gledali.', 'Ellos vieron.']] },
         { w: [['jučer', 'ayer'], ['sinoć', 'anoche']] }] },
  'Vocabulary 10': { h: 'Ayer y el tiempo libre', s: 'Películas, palabras de tiempo y frases para contar historias.',
    p2: [{ w: [['serija', 'serie'], ['komedija', 'comedia'], ['kazalište', 'teatro']] },
         { w: [['jučer', 'ayer'], ['sinoć', 'anoche'], ['nedavno', 'hace poco']] },
         { t: [['Kako je bilo?', '¿Qué tal estuvo?'], ['Bilo je super!', '¡Estuvo genial!']] }] },
  'Grammar 10': { h: 'El pasado',
    ex: [['Jučer sam gledao film.', 'Ayer vi una película.'], ['Nisam imao vremena.', "No tuve tiempo."]],
    p2: [{ g: [['on', 'ona', 'oni'], ['gledao', 'gledala', 'gledali'], ['bio', 'bila', 'bili']] },
         { w: [['sam', 'yo (hice)'], ['nisam', "yo no (hice)"]] }] },
  'Practice 10': { h: 'El fin de semana pasado', s: 'Un sábado tranquilo, la playa y un fin de semana en familia.',
    p2: [{ t: [['Gdje si bio jučer?', '¿Dónde estuviste ayer?'], ['Bio sam na moru.', 'Estuve en la playa.'], ['Plivao sam.', 'Nadé.']] }] },
  'Test 10': { h: 'Demuestra lo que sabes', s: 'El pasado y el tiempo libre.',
    p2: [{ g: [['on', 'ona', 'oni'], ['bio je', 'bila je', 'bili su']] },
         { w: [['nisam', "no estuve / no (hice)"]] }] },

  // ---------- 11 ----------
  'Lesson 11': { h: 'Hacer preguntas',
    ex: [['Što kupuješ?', '¿Qué compras?'], ['Koliko košta?', '¿Cuánto cuesta?']],
    p2: [{ t: [['Gdje živiš?', '¿Dónde vives?'], ['Voliš li kavu?', '¿Te gusta el café?'], ['Lijepo je, zar ne?', "Es lindo, ¿no?"]] },
         { w: [['jedan', '='], ['pet', '='], ['deset', '='], ['dvadeset', '=']] }] },
  'Vocabulary 11': { h: 'Preguntas y números', s: 'Palabras interrogativas, números y cumpleaños.',
    p2: [{ w: [['tko', 'quién'], ['što', 'qué'], ['gdje', 'dónde']] },
         { w: [['kada', 'cuándo'], ['zašto', 'por qué'], ['koliko', 'cuánto']] },
         { w: [['pet', 'cinco'], ['deset', 'diez'], ['sto', 'cien']] }] },
  'Grammar 11': { h: 'Tres formas de preguntar',
    ex: [['Kada dolaziš?', '¿Cuándo vienes?'], ['Voliš li kavu? — Volim.', '¿Te gusta el café? – Sí.']],
    p2: [{ t: [['Gdje si?', '¿Dónde estás?'], ['Jesi li umoran?', '¿Estás cansado?'], ['Umoran si, zar ne?', "Estás cansado, ¿verdad?"]] },
         { w: [['koji', 'cuál'], ['kakav', 'qué tipo de'], ['čiji', 'de quién']] }] },
  'Practice 11': { h: 'El misterio del regalo', s: 'Un regalo de cumpleaños, una caja misteriosa y un quiz.',
    p2: [{ t: [['Za koga?', '¿Para quién?'], ['Tko je poslao poklon?', '¿Quién mandó el regalo?'], ['Sretan rođendan!', '¡Feliz cumpleaños!']] }] },
  'Test 11': { h: 'Demuestra lo que sabes', s: 'Preguntas, números y precios.',
    p2: [{ t: [['Koliko košta?', '¿Cuánto cuesta?'], ['Koliko godina imaš?', '¿Cuántos años tienes?'], ['Imam dvadeset godina.', "Tengo veinte años."]] }] },

  // ---------- 12 ----------
  'Lesson 12': { h: 'Decir que no',
    ex: [['Ništa ne jedem.', "No como nada."], ['Nikad ne pijem mlijeko.', 'Nunca tomo leche.']],
    p2: [{ t: [['nisam', 'no soy / no estoy'], ['nemam', "no tengo"], ['neću', "no voy a / no (haré)"]] },
         { w: [['ništa', 'nada'], ['nitko', 'nadie'], ['nikad', 'nunca']] }] },
  'Vocabulary 12': { h: "Comida que (no) nos gusta", s: 'Comida, sabores y comer fuera.',
    p2: [{ w: [['piletina', 'pollo'], ['gljive', 'champiñones'], ['palačinke', 'panqueques']] },
         { w: [['slan', 'salado'], ['kiseo', 'ácido'], ['ljut', 'picante']] },
         { t: [['Dobar tek!', '¡Buen provecho!'], ['Račun, molim.', 'La cuenta, por favor.']] }] },
  'Grammar 12': { h: 'La negación',
    ex: [['Nitko ne kuha.', 'Nadie cocina.'], ['Ne pijem kavu, nego čaj.', "No tomo café, sino té."]],
    p2: [{ t: [['nešto → ništa', 'algo → nada'], ['netko → nitko', 'alguien → nadie'], ['nekad → nikad', 'a veces → nunca']] },
         { w: [['još ne', 'todavía no'], ['više ne', 'ya no']] }] },
  'Practice 12': { h: 'Los quisquillosos con la comida', s: 'Sopa, un restaurante y un niño que no come nada.',
    p2: [{ t: [['Ne volim juhu.', "No me gusta la sopa."], ['Imate li ribu?', '¿Tienen pescado?'], ['Nažalost, nemamo.', "Lo siento, no tenemos."]] }] },
  'Test 12': { h: 'Demuestra lo que sabes', s: 'Decir que no, y la comida.',
    p2: [{ t: [['Ništa ne jedem.', "No como nada."], ['Nemam vremena.', "No tengo tiempo."], ['Neću doći.', "No vendré."]] }] },

  // ---------- 13 ----------
  'Lesson 13': { h: '¿Dónde estás?',
    ex: [['Ja sam u gradu.', "Estoy en el centro."], ['Ana je u školi.', 'Ana está en la escuela.']],
    p2: [{ t: [['Idem u grad.', "Voy al centro."], ['Ja sam u gradu.', "Estoy en el centro."]] },
         { w: [['pošta', 'oficina de correos'], ['kuhinja', 'cocina'], ['gore', 'arriba']] }] },
  'Vocabulary 13': { h: 'Lugares y casa', s: 'Lugares de la ciudad, habitaciones y muebles.',
    p2: [{ w: [['pošta', 'oficina de correos'], ['ljekarna', 'farmacia'], ['luka', 'puerto']] },
         { w: [['kuhinja', 'cocina'], ['kupaonica', 'baño'], ['hodnik', 'pasillo']] },
         { w: [['gore', 'arriba'], ['dolje', 'abajo'], ['tamo', 'allí']] }] },
  'Grammar 13': { h: 'El locativo',
    ex: [['Radim u uredu.', 'Trabajo en una oficina.'], ['Pričam o tebi.', "Hablo de ti."]],
    p2: [{ g: [['grad', 'kino', 'škola'], ['u gradu', 'u kinu', 'u školi']] },
         { w: [['u banci', 'en el banco'], ['o meni', 'sobre mí']] }] },
  'Practice 13': { h: 'Por la ciudad', s: 'Un barrio, una llamada y una charla en familia.',
    p2: [{ t: [['Gdje si?', '¿Dónde estás?'], ['U autobusu sam.', "Estoy en el autobús."], ['Još sam u uredu.', "Todavía estoy en la oficina."]] }] },
  'Test 13': { h: 'Demuestra lo que sabes', s: 'Dónde están las personas y las cosas.',
    p2: [{ g: [['grad', 'more', 'škola'], ['u gradu', 'na moru', 'u školi']] }] },

  // ---------- 14 ----------
  'Lesson 14': { h: 'Hacer regalos',
    ex: [['Mami kupujem šal.', "Le compro una bufanda a mamá."], ['Pomažem bratu.', "Ayudo a mi hermano."]],
    p2: [{ t: [['mama → mami', 'a mamá'], ['tata → tati', 'a papá'], ['brat → bratu', 'a mi hermano']] },
         { w: [['paket', 'paquete'], ['igračka', 'juguete'], ['razglednica', 'postal']] }] },
  'Vocabulary 14': { h: 'Dar y receptores', s: 'Regalos, receptores y palabras de diciembre.',
    p2: [{ w: [['igračka', 'juguete'], ['ogrlica', 'collar'], ['kišobran', 'paraguas']] },
         { w: [['davati', 'dar'], ['slati', 'enviar'], ['donijeti', 'traer']] },
         { w: [['Božić', 'Navidad'], ['snijeg', 'nieve'], ['poruka', 'mensaje']] }] },
  'Grammar 14': { h: 'El dativo',
    ex: [['Baka mi šalje paket.', 'La abuela me manda un paquete.'], ['Meni, ne tebi!', '¡A mí, no a ti!']],
    p2: [{ g: [['a mí', 'a ti', 'a él', 'a ella'], ['mi', 'ti', 'mu', 'joj']] },
         { w: [['Komu?', '¿A quién?']] }] },
  'Practice 14': { h: 'Regalos de diciembre', s: 'Regalos, un cartero y una tarjeta de la abuela.',
    p2: [{ t: [['Komu pišeš?', '¿A quién le escribes?'], ['Pišem baki.', "Le escribo a la abuela."], ['Sretan Božić!', '¡Feliz Navidad!']] }] },
  'Test 14': { h: 'Demuestra lo que sabes', s: 'Darle algo a alguien y estar en algún lugar.',
    p2: [{ t: [['Dajem mami cvijeće.', 'Le doy flores a mamá.'], ['Mama je u kuhinji.', 'Mamá está en la cocina.']] }] },

  // ---------- 15 ----------
  'Lesson 15': { h: 'Salir',
    ex: [['Idem s Markom.', "Voy con Marko."], ['Idemo vlakom.', "Vamos en tren."]],
    p2: [{ t: [['s bratom', 'con mi hermano'], ['sa sestrom', 'con mi hermana'], ['tramvajem', 'en tranvía']] },
         { w: [['zabava', 'fiesta'], ['večera', 'cena'], ['izlazak', 'salida nocturna']] }] },
  'Vocabulary 15': { h: 'Salir y el clima', s: 'Una salida nocturna, el transporte y el clima.',
    p2: [{ w: [['zabava', 'fiesta'], ['večera', 'cena'], ['ples', 'baile']] },
         { w: [['trajekt', 'ferry'], ['skuter', 'scooter'], ['pješice', 'a pie']] },
         { w: [['kiša', 'lluvia'], ['vjetar', 'viento'], ['oblak', 'nube']] }] },
  'Grammar 15': { h: 'El instrumental',
    ex: [['Pišem olovkom.', 'Escribo con un lápiz.'], ['Idem s tobom.', "Voy contigo."]],
    p2: [{ g: [['brat', 'sestra', 'prijatelj'], ['bratom', 'sestrom', 'prijateljem']] },
         { w: [['sa mnom', 'conmigo'], ['s tobom', 'contigo']] }] },
  'Practice 15': { h: 'Viernes por la noche', s: 'Una salida, un viaje en tren y el menú de un café.',
    p2: [{ t: [['S kim ideš?', '¿Con quién vas?'], ['Sa sestrom.', 'Con mi hermana.'], ['Kava s mlijekom', 'Café con leche']] }] },
  'Test 15': { h: 'Demuestra lo que sabes', s: 'Cuatro casos, una palabra.',
    p2: [{ t: [['Vidim mamu.', 'Veo a mamá.'], ['Pišem mami.', "Le escribo a mamá."], ['Pričam o mami.', "Hablo de mamá."], ['Idem s mamom.', "Voy con mamá."]] }] },

  // ---------- 16 ----------
  'Lesson 16': { h: "La casa de la abuela",
    ex: [['Kava bez šećera.', 'Café sin azúcar.'], ['Nema problema!', '¡No hay problema!']],
    p2: [{ t: [['kod bake', "en casa de la abuela"], ['iz Zagreba', 'de Zagreb'], ['pokraj kuće', 'junto a la casa']] },
         { w: [['vrt', 'jardín'], ['vrata', 'puerta'], ['miris', 'olor']] }] },
  'Vocabulary 16': { h: 'Casa y hogar', s: 'Palabras de la casa y palabritas para lugares.',
    p2: [{ w: [['miris', 'olor'], ['boja', 'color'], ['slika', 'imagen']] },
         { w: [['bez', 'sin'], ['iz', 'de (desde)'], ['kod', 'en casa de']] },
         { w: [['ispred', 'delante de'], ['iza', 'detrás de'], ['ispod', 'debajo de']] }] },
  'Grammar 16': { h: 'El genitivo',
    ex: [['kuća moje bake', "la casa de mi abuela"], ['Dvije kave, molim.', 'Dos cafés, por favor.']],
    p2: [{ g: [['grad', 'kava', 'noć'], ['grada', 'kave', 'noći']] },
         { w: [['jedna kava', 'un café'], ['pet kava', 'cinco cafés']] }] },
  'Practice 16': { h: 'El camino al mar', s: "La casa de la abuela, un café y un viaje en auto a la costa.",
    p2: [{ t: [['Pokraj kuće je vrt.', 'Junto a la casa hay un jardín.'], ['Jedan čaj za Marka.', 'Un té para Marko.'], ['Putujemo iz Zagreba.', "Viajamos desde Zagreb."]] }] },
  'Test 16': { h: 'Demuestra lo que sabes', s: 'El genitivo y la casa.',
    p2: [{ g: [['grad', 'baka', 'more'], ['iz grada', 'kod bake', 'do mora']] }] },

  // ---------- 17 ----------
  'Lesson 17': { h: 'Dar órdenes',
    ex: [['Uzmi tri jaja.', 'Toma tres huevos.'], ['Skrenite lijevo.', 'Gire a la izquierda.']],
    p2: [{ t: [['Gledaj!', '¡Mira!'], ['Uzmi!', '¡Toma!'], ['Pij!', '¡Bebe!']] },
         { w: [['lijevo', 'izquierda'], ['desno', 'derecha'], ['ravno', 'todo recto']] }] },
  'Vocabulary 17': { h: 'Recetas e indicaciones', s: 'Palabras de cocina, órdenes e indicaciones.',
    p2: [{ w: [['brašno', 'harina'], ['tava', 'sartén'], ['ulje', 'aceite']] },
         { w: [['uzmi', 'toma'], ['dodaj', 'agrega'], ['miješaj', 'mezcla']] },
         { w: [['lijevo', 'izquierda'], ['desno', 'derecha'], ['ravno', 'todo recto']] }] },
  'Grammar 17': { h: 'El imperativo',
    ex: [['Gledajte!', '¡Miren! (ustedes)'], ['Možeš li mi pomoći?', '¿Me puedes ayudar?']],
    p2: [{ g: [['ti', 'vi', "vamos a…"], ['gledaj', 'gledajte', 'gledajmo']] },
         { w: [['mogu', 'puedo'], ['moram', 'debo'], ['hoću', 'quiero']] }] },
  'Practice 17': { h: 'Recetas e indicaciones', s: 'Panqueques, buscar la estación y un entrenador estricto.',
    p2: [{ t: [['Gdje je kolodvor?', '¿Dónde está la estación?'], ['Idite ravno.', 'Siga todo recto.'], ['Pij vodu!', '¡Bebe agua!']] }] },
  'Test 17': { h: 'Demuestra lo que sabes', s: 'Órdenes, recetas e indicaciones.',
    p2: [{ g: [['ti', 'vi'], ['gledaj', 'gledajte'], ['uzmi', 'uzmite'], ['pij', 'pijte']] }] },

  // ---------- 18 ----------
  'Lesson 18': { h: 'Un millón de euros',
    ex: [['Kupio bih kuću.', 'Compraría una casa.'], ['Htjela bih kavu.', "Quisiera un café."]],
    p2: [{ t: [['Kupio bih...', 'Compraría... (él)'], ['Kupila bih...', 'Compraría... (ella)'], ['Biste li mogli...?', '¿Podría...? / ¿Podrían...?']] },
         { w: [['san', 'sueño'], ['sreća', 'felicidad'], ['ako', 'si']] }] },
  'Vocabulary 18': { h: 'Deseos y sentimientos', s: 'Sueños, sentimientos y el condicional.',
    p2: [{ w: [['san', 'sueño'], ['jahta', 'yate'], ['vila', 'villa']] },
         { w: [['sreća', 'felicidad'], ['strah', 'miedo'], ['nada', 'esperanza']] },
         { w: [['sanjati', 'soñar'], ['nadati se', 'esperar (tener esperanza)'], ['bojati se', 'tener miedo']] }] },
  'Grammar 18': { h: 'El condicional',
    ex: [['Išli bismo na more.', 'Iríamos al mar.'], ['Ne bih žurila.', "No me apuraría."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['bih', 'bi', 'bi'], ['mi', 'vi', 'oni'], ['bismo', 'biste', 'bi']], gh: [0, 2] }] },
  'Practice 18': { h: 'Sueños y días perfectos', s: 'Sueños de lotería, un día perfecto y una encuesta en la calle.',
    p2: [{ t: [['Prvo bih kupio kuću.', "Primero compraría una casa."], ['Svaki dan bih plivala.', "Nadaría todos los días."], ['Što biste radili?', '¿Qué harían?']] }] },
  'Test 18': { h: 'Demuestra lo que sabes', s: 'Deseos, sueños y sentimientos.',
    p2: [{ g: [['él', 'ella'], ['kupio bih', 'kupila bih'], ['htio bih', 'htjela bih']] }] },

  // ---------- 19 ----------
  'Lesson 19': { h: 'Verbos gemelos',
    ex: [['Pisao sam pismo.', 'Estaba escribiendo una carta.'], ['Napisao sam pismo.', 'Terminé la carta.']],
    p2: [{ t: [['pisati → napisati', 'escribir → terminar de escribir'], ['piti → popiti', 'beber → beberse todo'], ['čitati → pročitati', 'leer → leerlo todo']] },
         { w: [['dugo', 'por mucho tiempo'], ['napokon', 'por fin'], ['odmah', 'enseguida']] }] },
  'Vocabulary 19': { h: 'Historias y sucesos', s: 'Pares de verbos, palabras de tiempo y palabras para historias.',
    p2: [{ t: [['učiti → naučiti', 'estudiar → aprender'], ['kupovati → kupiti', 'ir de compras → comprar']] },
         { w: [['napokon', 'por fin'], ['odjednom', 'de repente'], ['već', 'ya']] }] },
  'Grammar 19': { h: '¿Terminado o no?',
    ex: [['Ana je učila cijelu večer.', 'Ana estudió toda la noche.'], ['Naučila je sve.', 'Lo aprendió todo.']],
    p2: [{ g: [['en curso', 'terminado'], ['pisati', 'napisati'], ['piti', 'popiti'], ['kupovati', 'kupiti']] }] },
  'Practice 19': { h: 'La carta', s: 'Una carta larga, la tarea y una lista para el sábado.',
    p2: [{ t: [['Jesi li napisao zadaću?', '¿Terminaste tu tarea?'], ['Skoro!', '¡Casi!'], ['Napokon!', '¡Por fin!']] }] },
  'Test 19': { h: 'Demuestra lo que sabes', s: 'Pares de verbos: en curso o terminado.',
    p2: [{ g: [['en curso', 'terminado'], ['pisati', 'napisati'], ['čitati', 'pročitati'], ['raditi', 'napraviti']] }] },

  // ---------- 20 ----------
  'Lesson 20': { h: 'Oraciones largas',
    ex: [['Ostajem doma jer pada kiša.', "Me quedo en casa porque llueve."], ['Ako je sunčano, idemo van.', "Si hace sol, salimos."]],
    p2: [{ t: [['jer', 'porque'], ['kad', 'cuando'], ['ako', 'si'], ['iako', 'aunque']] },
         { w: [['koji', 'que, quien'], ['da', 'que']] }] },
  'Vocabulary 20': { h: 'Recuerdos y oraciones largas', s: 'Palabras para unir, recuerdos de verano y aprendizaje.',
    p2: [{ w: [['jer', 'porque'], ['kad', 'cuando'], ['ako', 'si']] },
         { w: [['dok', 'mientras'], ['iako', 'aunque'], ['kao', 'como']] },
         { w: [['uspomena', 'recuerdo'], ['otok', 'isla'], ['galeb', 'gaviota']] }] },
  'Grammar 20': { h: 'Oraciones complejas',
    ex: [['Mislim da ćeš doći.', "Creo que vendrás."], ['film koji gledam', "la película que estoy viendo"]],
    p2: [{ t: [['Kad dođeš, zovi me.', 'Cuando vengas, llámame.'], ['Znam da je velik.', 'Sé que es grande.']] },
         { w: [['da', 'que'], ['koji', 'que, quien']] }] },
  'Practice 20': { h: 'El verano que recuerdo', s: 'Un verano en una isla, una redacción y una postal.',
    p2: [{ t: [['Pozdrav s otoka!', '¡Saludos desde la isla!'], ['Draga bako,', 'Querida abuela:'], ['Učim hrvatski jer...', "Aprendo croata porque..."]] }] },
  'Test 20': { h: 'La prueba final', s: 'Todo lo de las 20 lecciones.',
    p2: [{ t: [['Učim.', "Aprendo."], ['Učio sam.', 'Aprendí.'], ['Učit ću.', 'Aprenderé.'], ['Učio bih.', 'Aprendería.']] }] }
};
