// Kratki pregledi cjelina — prozor koji se otvori klikom na cjelinu u izborniku Lessons.
// Uređuje se ručno (ne generira ga osvjezi.js).
//   h  = naslov (stranica 1)
//   s  = jedna kratka rečenica ispod naslova (nije obavezno)
//   ex = 1–2 primjera [hrvatski, engleski] (stranica 1, nije obavezno)
//   p2 = stranica 2, popis blokova:
//        { t: [[hr, en], ...] }       tablica: hrvatski lijevo, prijevod desno
//        { g: [[zaglavlje...], [redak...], ...] }  mala mreža, prvi redak je zaglavlje
//              (gh: [0, 2] = koji su retci zaglavlja, ako ih je više)
//        { w: [[hr, en], ...] }       riječi u jednom retku
// Broj koraka, prag i trajanje testa prozor čita iz data.js.
window.PREGLEDI = {
  // ---------- 1 ----------
  'Lesson 1': { h: 'Deine ersten kroatischen Sätze',
    ex: [['Kava je dobra.', 'Der Kaffee ist gut.'], ['More je plavo.', 'Das Meer ist blau.']],
    p2: [{ t: [['Grad je velik.', 'Die Stadt ist groß.'], ['Kuća je velika.', 'Das Haus ist groß.'], ['More je veliko.', 'Das Meer ist groß.']] },
         { w: [['kuća', 'house'], ['grad', 'city'], ['more', 'sea'], ['kava', 'coffee']] }] },
  'Vocabulary 1': { h: 'Dinge, Farben und Größen', s: 'Etwa 40 Alltagswörter.',
    p2: [{ w: [['soba', 'room'], ['stol', 'table'], ['knjiga', 'book']] },
         { w: [['crven', 'red'], ['plav', 'blue'], ['žut', 'yellow']] },
         { w: [['velik', 'big'], ['mali', 'small'], ['nov', 'new']] }] },
  'Grammar 1': { h: 'Endungen, die zusammenpassen',
    ex: [['Kuća je velika.', 'Das Haus ist groß.'], ['Kava nije dobra.', "Der Kaffee ist nicht gut."]],
    p2: [{ g: [['grad', 'kuća', 'more'], ['velik', 'velika', 'veliko']] },
         { w: [['je', 'wartet'], ['nije', "isn't"]] }] },
  'Practice 1': { h: 'Lies deine ersten Texte', s: 'Eine Stadt, ein Zimmer und ein Café.',
    p2: [{ t: [['Kava, molim.', 'Einen Kaffee, bitte.'], ['Izvolite.', 'Bitte schön.'], ['Hvala!', 'Danke!']] }] },
  'Test 1': { h: 'Zeig, was du kannst', s: 'Wörter, Endungen und einfache Sätze.',
    p2: [{ g: [['grad', 'kuća', 'more'], ['star', 'stara', 'staro']] },
         { w: [['je', 'wartet'], ['nije', "isn't"]] }] },

  // ---------- 2 ----------
  'Lesson 2': { h: 'Über Menschen sprechen',
    ex: [['Ja sam studentica.', 'Ich bin Studentin.'], ['Ona je visoka.', 'Sie ist groß.']],
    p2: [{ t: [['Ja sam Ana.', 'Ich bin Ana.'], ['Ti si Marko.', 'Du bist Marko.'], ['Oni su veseli.', 'Sie sind fröhlich.']] },
         { w: [['ja', 'I'], ['ti', 'you'], ['on', 'he'], ['ona', 'she']] }] },
  'Vocabulary 2': { h: 'Berufe, Länder, Charakter', s: 'Wörter für Menschen und deine ersten Begrüßungen.',
    p2: [{ w: [['kuhar', 'cook'], ['vozač', 'driver'], ['učitelj', 'teacher']] },
         { w: [['Hrvat', 'Kroate'], ['Talijan', 'Italiener'], ['Nijemac', 'Deutscher']] },
         { t: [['Kako si?', 'Wie geht\'s dir?'], ['Dobro sam.', "Mir geht's gut."]] }] },
  'Grammar 2': { h: 'Das Verb „sein“',
    ex: [['Mi smo turisti.', 'Wir sind Touristen.'], ['Nisam gladan.', "Ich habe keinen Hunger."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['sam', 'si', 'je'], ['mi', 'vi', 'oni'], ['smo', 'ste', 'su']], gh: [0, 2] }] },
  'Practice 2': { h: 'Neue Leute kennenlernen', s: 'Vorstellungen, ein Café und ein Team.',
    p2: [{ t: [['Tko si ti?', 'Wer bist du?'], ['Kako ste?', 'Wie geht\'s dir?'], ['Dobro sam, hvala.', "Mir geht's gut, danke."]] }] },
  'Test 2': { h: 'Zeig, was du kannst', s: 'Menschen, „sein“ und Vorstellungen.',
    p2: [{ g: [['on', 'ona', 'oni'], ['visok', 'visoka', 'visoki']] },
         { w: [['sam', 'ich bin'], ['smo', 'wir sind'], ['su', 'sie sind']] }] },

  // ---------- 3 ----------
  'Lesson 3': { h: 'Was du tust',
    ex: [['Pijem čaj.', "Ich trinke Tee."], ['Ana radi.', 'Ana arbeitet.']],
    p2: [{ t: [['čitam', 'ich lese'], ['čitaš', 'du liest'], ['čita', 'er / sie liest']] },
         { w: [['piti', 'drink'], ['jesti', 'eat'], ['raditi', 'work'], ['spavati', 'sleep']] }] },
  'Vocabulary 3': { h: 'Alltagsverben', s: 'Verben und was dazugehört.',
    p2: [{ w: [['čitati', 'read'], ['pisati', 'write'], ['piti', 'drink']] },
         { w: [['kruh', 'bread'], ['sir', 'cheese'], ['čaj', 'tea']] },
         { w: [['uvijek', 'always'], ['često', 'often'], ['nikad', 'never']] }] },
  'Grammar 3': { h: 'Das Präsens',
    ex: [['Učim hrvatski.', "Ich lerne Kroatisch."], ['Ne pijem sok.', "Ich trinke keinen Saft."]],
    p2: [{ g: [['čitati', 'raditi', 'pisati'], ['čitam', 'radim', 'pišem'], ['čitaš', 'radiš', 'pišeš'], ['čita', 'radi', 'piše']] }] },
  'Practice 3': { h: 'Ein Tag voller Tätigkeiten', s: 'Eine Wohnung, ein Abend und ein ruhiger Sonntag.',
    p2: [{ t: [['Što radiš?', 'Was machst du?'], ['Učim hrvatski.', "Ich lerne Kroatisch."], ['Gledam film.', "Ich schaue einen Film."]] }] },
  'Test 3': { h: 'Zeig, was du kannst', s: 'Alltagsverben im Präsens.',
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['pijem', 'piješ', 'pije']] },
         { w: [['ne pijem', "ich trinke nicht"]] }] },

  // ---------- 4 ----------
  'Lesson 4': { h: 'Die Familie',
    ex: [['Tata kuha, a brat uči.', 'Papa kocht, mein Bruder lernt.'], ['Mama radi i čita.', 'Mama arbeitet und liest.']],
    p2: [{ t: [['i', 'and'], ['a', 'und, während'], ['ali', 'but']] },
         { w: [['mama', 'mum'], ['tata', 'dad'], ['brat', 'brother'], ['sestra', 'sister']] }] },
  'Vocabulary 4': { h: 'Familie und Zuhause', s: 'Engste Familie, weitere Familie und neue Verben.',
    p2: [{ w: [['mama', 'mum'], ['tata', 'dad'], ['baka', 'grandma']] },
         { w: [['brat', 'brother'], ['sestra', 'sister'], ['dijete', 'child']] },
         { w: [['imati', 'have'], ['kuhati', 'cook'], ['živjeti', 'live']] }] },
  'Grammar 4': { h: 'Sätze verbinden',
    ex: [['Mama radi i čita.', 'Mama arbeitet und liest.'], ['Ne plivam jer je hladno.', "Ich schwimme nicht, weil es kalt ist."]],
    p2: [{ t: [['i', 'and'], ['a', 'und, während'], ['ali', 'but'], ['jer', 'because']] }] },
  'Practice 4': { h: 'Familienleben', s: 'Eine Familie, ein hektischer Morgen und ein Samstag zu Hause.',
    p2: [{ t: [['Ovo je obitelj.', 'Das ist eine Familie.'], ['Što radiš danas?', 'Was machst du heute?'], ['Baka kuha.', 'Oma kocht.']] }] },
  'Test 4': { h: 'Zeig, was du kannst', s: 'Familienwörter, Verben und Bindewörter.',
    p2: [{ t: [['i', 'and'], ['a', 'und, während'], ['ali', 'but'], ['jer', 'because']] }] },

  // ---------- 5 ----------
  'Lesson 5': { h: 'Einkaufen',
    ex: [['Pijem kavu.', "Ich trinke Kaffee."], ['Trebate li vrećicu?', 'Brauchen Sie eine Tüte?']],
    p2: [{ t: [['Kava je dobra.', 'Der Kaffee ist gut.'], ['Pijem kavu.', "Ich trinke Kaffee."], ['Jedem jabuku.', "Ich esse einen Apfel."]] },
         { w: [['kruh', 'bread'], ['voda', 'water'], ['sir', 'cheese'], ['riba', 'fish']] }] },
  'Vocabulary 5': { h: 'Einkaufen und Essen', s: 'Marktwörter und 10 neue Verben.',
    p2: [{ w: [['voda', 'water'], ['juha', 'soup'], ['riža', 'rice']] },
         { w: [['kruh', 'bread'], ['mlijeko', 'milk'], ['meso', 'meat']] },
         { w: [['kupovati', 'buy'], ['trebati', 'need'], ['plaćati', 'pay']] }] },
  'Grammar 5': { h: 'Dein erster Fall',
    ex: [['Kupujem svježu salatu.', "Ich kaufe frischen Salat."], ['Idem u trgovinu.', "Ich gehe in den Laden."]],
    p2: [{ g: [['kava', 'crna kava'], ['Pijem kavu.', 'Pijem crnu kavu.']] },
         { w: [['u trgovinu', 'in den Laden'], ['na tržnicu', 'auf den Markt']] }] },
  'Practice 5': { h: 'Auf dem Markt', s: 'Ein Markt, ein Zettel am Kühlschrank und Frühstück.',
    p2: [{ t: [['Ana kupuje jabuku.', 'Ana kauft einen Apfel.'], ['Trebamo kruh i rižu.', 'Wir brauchen Brot und Reis.'], ['Volim kavu!', 'Ich liebe Kaffee!']] }] },
  'Test 5': { h: 'Zeig, was du kannst', s: 'Essen, Einkaufen und dein erster Fall.',
    p2: [{ g: [['kava', 'juha', 'salata'], ['kavu', 'juhu', 'salatu']] },
         { w: [['kruh', 'Brot (keine Änderung)']] }] },

  // ---------- 6 ----------
  'Lesson 6': { h: 'In der Stadt',
    ex: [['Vidim prijatelja.', 'Ich sehe einen Freund.'], ['Čekam tramvaj.', "Ich warte auf die Straßenbahn."]],
    p2: [{ t: [['Vidim prijatelja.', 'Ich sehe einen Freund.'], ['Vidim tramvaj.', 'Ich sehe eine Straßenbahn.'], ['Vidim psa.', 'Ich sehe einen Hund.']] },
         { w: [['ulica', 'street'], ['trg', 'square'], ['most', 'bridge']] }] },
  'Vocabulary 6': { h: 'Die Stadt und der Verkehr', s: 'Menschen, Verkehrsmittel und Orte in der Stadt.',
    p2: [{ w: [['tramvaj', 'tram'], ['vlak', 'train'], ['bicikl', 'bike']] },
         { w: [['ulica', 'street'], ['trg', 'square'], ['most', 'bridge']] },
         { w: [['vidjeti', 'see'], ['čuti', 'hear'], ['voziti', 'drive']] }] },
  'Grammar 6': { h: 'Menschen und Dinge',
    ex: [['Čekam prijatelja.', "Ich warte auf einen Freund."], ['Vidim ga.', 'Ich sehe ihn.']],
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['me', 'me'], ['te', 'you'], ['ga', 'him'], ['je', 'her']] }] },
  'Practice 6': { h: 'Stadtleben', s: 'Eine Straßenbahnfahrt, eine belebte Straße und ein verlorener Hund.',
    p2: [{ t: [['Ana čeka tramvaj.', 'Ana wartet auf die Straßenbahn.'], ['Tramvaj je pun.', 'Die Straßenbahn ist voll.'], ['Oprostite!', 'Entschuldigung!']] }] },
  'Test 6': { h: 'Zeig, was du kannst', s: 'Die Stadt und der ganze erste Fall.',
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['ga', 'ihn, es'], ['je', 'her']] }] },

  // ---------- 7 ----------
  'Lesson 7': { h: 'In der Schule: mehr als eins',
    ex: [['Knjige su nove.', 'Die Bücher sind neu.'], ['Učenici pjevaju.', 'Die Schüler singen.']],
    p2: [{ g: [['učenik', 'knjiga', 'pismo'], ['učenici', 'knjige', 'pisma']] },
         { w: [['škola', 'school'], ['olovka', 'pencil'], ['ispit', 'exam']] }] },
  'Vocabulary 7': { h: 'Schule und Lieder', s: 'Schulwörter, Plural und 10 neue Verben.',
    p2: [{ w: [['škola', 'school'], ['olovka', 'pencil'], ['torba', 'bag']] },
         { w: [['ispit', 'exam'], ['ocjena', 'grade'], ['zadaća', 'homework']] },
         { w: [['pjevati', 'sing'], ['igrati', 'play'], ['znati', 'know']] }] },
  'Grammar 7': { h: 'Der Plural',
    ex: [['Stolovi su stari.', 'Die Tische sind alt.'], ['Djeca pjevaju.', 'Die Kinder singen.']],
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['čitamo', 'čitate', 'čitaju']] }] },
  'Practice 7': { h: 'Schultage', s: 'Eine Schule, ein Stundenplan, ein Chor und neue Schüler.',
    p2: [{ t: [['Dobro jutro, djeco!', 'Guten Morgen, Kinder!'], ['Djeca pjevaju.', 'Die Kinder singen.'], ['Knjige su nove.', 'Die Bücher sind neu.']] }] },
  'Test 7': { h: 'Zeig, was du kannst', s: 'Nomen, Adjektive und Verben im Plural.',
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['pjevamo', 'pjevate', 'pjevaju']] }] },

  // ---------- 8 ----------
  'Lesson 8': { h: 'Sommerpläne',
    ex: [['Plivat ću.', 'Ich werde schwimmen.'], ['Mi ćemo putovati.', 'Wir werden reisen.']],
    p2: [{ t: [['Plivat ću.', 'Ich werde schwimmen.'], ['Putovat ćemo u subotu.', 'Wir werden am Samstag reisen.'], ['Neću plivati.', "Ich werde nicht schwimmen."]] },
         { w: [['plaža', 'beach'], ['otok', 'island'], ['sutra', 'tomorrow']] }] },
  'Vocabulary 8': { h: 'Pläne und Reisen', s: 'Urlaub, Tage, Kleidung und 10 neue Verben.',
    p2: [{ w: [['plaža', 'beach'], ['otok', 'island'], ['kofer', 'suitcase']] },
         { w: [['sutra', 'tomorrow'], ['vikend', 'weekend'], ['tjedan', 'week']] },
         { w: [['putovati', 'travel'], ['plivati', 'swim'], ['letjeti', 'fly']] }] },
  'Grammar 8': { h: 'Das Futur',
    ex: [['Sutra ću plivati.', 'Morgen werde ich schwimmen.'], ['Neću raditi.', "Ich werde nicht arbeiten."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['ću', 'ćeš', 'će'], ['mi', 'vi', 'oni'], ['ćemo', 'ćete', 'će']], gh: [0, 2] }] },
  'Practice 8': { h: 'Pläne und Fahrten', s: 'Ein Sommerplan, eine Packliste und eine Zugfahrkarte.',
    p2: [{ t: [['Ići ćemo u Split.', 'Wir werden nach Split fahren.'], ['Ustat ću rano.', 'Ich werde früh aufstehen.'], ['Tata će voziti.', 'Papa wird fahren.']] }] },
  'Test 8': { h: 'Zeig, was du kannst', s: 'Pläne, Reisen und das Futur.',
    p2: [{ t: [['Plivat ću.', 'Ich werde schwimmen.'], ['Ja ću plivati.', 'Ich werde schwimmen.'], ['Neću plivati.', "Ich werde nicht schwimmen."]] }] },

  // ---------- 9 ----------
  'Lesson 9': { h: 'Sport und Hobbys',
    ex: [['Moj hobi je fotografija.', 'Mein Hobby ist Fotografie.'], ['Boli me koljeno.', 'Mein Knie tut weh.']],
    p2: [{ t: [['moj dres', 'mein Trikot'], ['moja lopta', 'mein Ball'], ['moje koljeno', 'mein Knie']] },
         { w: [['glava', 'head'], ['ruka', 'arm'], ['noga', 'leg'], ['srce', 'heart']] }] },
  'Vocabulary 9': { h: 'Sport, Körper und „mein“', s: 'Sportwörter, der Körper und wem was gehört.',
    p2: [{ w: [['klub', 'club'], ['trener', 'coach'], ['igrač', 'player']] },
         { w: [['glava', 'head'], ['ruka', 'arm'], ['noga', 'leg']] },
         { w: [['moj', 'my'], ['tvoj', 'your'], ['naš', 'our']] }] },
  'Grammar 9': { h: 'Mein, dein, unser',
    ex: [['njegova gitara', 'seine Gitarre'], ['Marko voli svoju sestru.', 'Marko liebt seine (eigene) Schwester.']],
    p2: [{ g: [['moj', 'moja', 'moje'], ['njegov', 'njegova', 'njegovo'], ['njezin', 'njezina', 'njezino']] },
         { w: [['svoj', 'mein / sein / ihr eigener'], ['čiji', 'whose']] }] },
  'Practice 9': { h: 'Unser Verein, mein Hobby', s: 'Ein Hobby, ein verlorener Ball und ein Fußballverein.',
    p2: [{ t: [['Je li ovo tvoja lopta?', 'Ist das dein Ball?'], ['Da, moja je!', "Ja, das ist meiner!"], ['Naš klub je mali.', 'Unser Verein ist klein.']] }] },
  'Test 9': { h: 'Zeig, was du kannst', s: 'Possessivpronomen, Sport und der Körper.',
    p2: [{ g: [['dres', 'lopta', 'koljeno'], ['moj', 'moja', 'moje']] },
         { w: [['svoj', 'mein / sein / ihr eigener']] }] },

  // ---------- 10 ----------
  'Lesson 10': { h: 'Gestern',
    ex: [['Gledao sam film.', 'Ich habe einen Film geschaut.'], ['Bilo je savršeno.', 'Es war perfekt.']],
    p2: [{ t: [['On je gledao.', 'Er hat geschaut.'], ['Ona je gledala.', 'Sie hat geschaut.'], ['Oni su gledali.', 'Sie haben geschaut.']] },
         { w: [['jučer', 'yesterday'], ['sinoć', 'gestern Abend']] }] },
  'Vocabulary 10': { h: 'Gestern und Freizeit', s: 'Filme, Zeitwörter und Wendungen zum Erzählen.',
    p2: [{ w: [['serija', 'series'], ['komedija', 'comedy'], ['kazalište', 'theatre']] },
         { w: [['jučer', 'yesterday'], ['sinoć', 'gestern Abend'], ['nedavno', 'recently']] },
         { t: [['Kako je bilo?', 'Wie war es?'], ['Bilo je super!', 'Es war super!']] }] },
  'Grammar 10': { h: 'Die Vergangenheit',
    ex: [['Jučer sam gledao film.', 'Gestern habe ich einen Film geschaut.'], ['Nisam imao vremena.', "Ich hatte keine Zeit."]],
    p2: [{ g: [['on', 'ona', 'oni'], ['gledao', 'gledala', 'gledali'], ['bio', 'bila', 'bili']] },
         { w: [['sam', 'ich (habe gemacht)'], ['nisam', "ich habe nicht"]] }] },
  'Practice 10': { h: 'Letztes Wochenende', s: 'Ein fauler Samstag, das Meer und ein Familienwochenende.',
    p2: [{ t: [['Gdje si bio jučer?', 'Wo warst du gestern?'], ['Bio sam na moru.', 'Ich war am Meer.'], ['Plivao sam.', 'Ich bin geschwommen.']] }] },
  'Test 10': { h: 'Zeig, was du kannst', s: 'Die Vergangenheit und Freizeit.',
    p2: [{ g: [['on', 'ona', 'oni'], ['bio je', 'bila je', 'bili su']] },
         { w: [['nisam', "ich war nicht / habe nicht"]] }] },

  // ---------- 11 ----------
  'Lesson 11': { h: 'Fragen stellen',
    ex: [['Što kupuješ?', 'Was kaufst du?'], ['Koliko košta?', 'Wie viel kostet das?']],
    p2: [{ t: [['Gdje živiš?', 'Wo wohnst du?'], ['Voliš li kavu?', 'Magst du Kaffee?'], ['Lijepo je, zar ne?', "Schön, nicht wahr?"]] },
         { w: [['jedan', '1'], ['pet', '5'], ['deset', '10'], ['dvadeset', '20']] }] },
  'Vocabulary 11': { h: 'Fragen und Zahlen', s: 'Fragewörter, Zahlen und Geburtstage.',
    p2: [{ w: [['tko', 'who'], ['što', 'what'], ['gdje', 'where']] },
         { w: [['kada', 'when'], ['zašto', 'why'], ['koliko', 'wie viel']] },
         { w: [['pet', 'five'], ['deset', 'ten'], ['sto', 'hundert']] }] },
  'Grammar 11': { h: 'Drei Arten zu fragen',
    ex: [['Kada dolaziš?', 'Wann kommst du?'], ['Voliš li kavu? — Volim.', 'Magst du Kaffee? – Ja.']],
    p2: [{ t: [['Gdje si?', 'Wo bist du?'], ['Jesi li umoran?', 'Bist du müde?'], ['Umoran si, zar ne?', "Du bist müde, oder?"]] },
         { w: [['koji', 'which'], ['kakav', 'was für ein'], ['čiji', 'whose']] }] },
  'Practice 11': { h: 'Das Geschenkrätsel', s: 'Ein Geburtstagsgeschenk, eine geheimnisvolle Kiste und ein Quiz.',
    p2: [{ t: [['Za koga?', 'Für wen?'], ['Tko je poslao poklon?', 'Wer hat das Geschenk geschickt?'], ['Sretan rođendan!', 'Alles Gute zum Geburtstag!']] }] },
  'Test 11': { h: 'Zeig, was du kannst', s: 'Fragen, Zahlen und Preise.',
    p2: [{ t: [['Koliko košta?', 'Wie viel kostet das?'], ['Koliko godina imaš?', 'Wie alt bist du?'], ['Imam dvadeset godina.', "Ich bin zwanzig."]] }] },

  // ---------- 12 ----------
  'Lesson 12': { h: 'Nein sagen',
    ex: [['Ništa ne jedem.', "Ich esse nichts."], ['Nikad ne pijem mlijeko.', 'Ich trinke nie Milch.']],
    p2: [{ t: [['nisam', 'ich bin nicht'], ['nemam', "ich habe nicht"], ['neću', "ich werde nicht"]] },
         { w: [['ništa', 'nothing'], ['nitko', 'nobody'], ['nikad', 'never']] }] },
  'Vocabulary 12': { h: "Essen, das wir (nicht) mögen", s: 'Essen, Geschmack und auswärts essen.',
    p2: [{ w: [['piletina', 'chicken'], ['gljive', 'mushrooms'], ['palačinke', 'pancakes']] },
         { w: [['slan', 'salty'], ['kiseo', 'sour'], ['ljut', 'spicy']] },
         { t: [['Dobar tek!', 'Guten Appetit!'], ['Račun, molim.', 'Die Rechnung, bitte.']] }] },
  'Grammar 12': { h: 'Verneinung',
    ex: [['Nitko ne kuha.', 'Niemand kocht.'], ['Ne pijem kavu, nego čaj.', "Ich trinke keinen Kaffee, sondern Tee."]],
    p2: [{ t: [['nešto → ništa', 'etwas → nichts'], ['netko → nitko', 'jemand → niemand'], ['nekad → nikad', 'manchmal → nie']] },
         { w: [['još ne', 'noch nicht'], ['više ne', 'nicht mehr']] }] },
  'Practice 12': { h: 'Die heiklen Esser', s: 'Suppe, ein Restaurant und ein Kind, das nichts isst.',
    p2: [{ t: [['Ne volim juhu.', "Ich mag keine Suppe."], ['Imate li ribu?', 'Haben Sie Fisch?'], ['Nažalost, nemamo.', "Leider nicht."]] }] },
  'Test 12': { h: 'Zeig, was du kannst', s: 'Nein sagen, und Essen.',
    p2: [{ t: [['Ništa ne jedem.', "Ich esse nichts."], ['Nemam vremena.', "Ich habe keine Zeit."], ['Neću doći.', "Ich komme nicht."]] }] },

  // ---------- 13 ----------
  'Lesson 13': { h: 'Wo bist du?',
    ex: [['Ja sam u gradu.', "Ich bin in der Stadt."], ['Ana je u školi.', 'Ana ist in der Schule.']],
    p2: [{ t: [['Idem u grad.', "Ich gehe in die Stadt."], ['Ja sam u gradu.', "Ich bin in der Stadt."]] },
         { w: [['pošta', 'Post'], ['kuhinja', 'kitchen'], ['gore', 'upstairs']] }] },
  'Vocabulary 13': { h: 'Orte und Zuhause', s: 'Orte in der Stadt, Zimmer und Möbel.',
    p2: [{ w: [['pošta', 'Post'], ['ljekarna', 'pharmacy'], ['luka', 'harbour']] },
         { w: [['kuhinja', 'kitchen'], ['kupaonica', 'bathroom'], ['hodnik', 'hall']] },
         { w: [['gore', 'up'], ['dolje', 'down'], ['tamo', 'there']] }] },
  'Grammar 13': { h: 'Der Lokativ',
    ex: [['Radim u uredu.', 'Ich arbeite in einem Büro.'], ['Pričam o tebi.', "Ich rede über dich."]],
    p2: [{ g: [['grad', 'kino', 'škola'], ['u gradu', 'u kinu', 'u školi']] },
         { w: [['u banci', 'in der Bank'], ['o meni', 'über mich']] }] },
  'Practice 13': { h: 'Unterwegs in der Stadt', s: 'Ein Viertel, ein Telefonat und ein Familiengespräch.',
    p2: [{ t: [['Gdje si?', 'Wo bist du?'], ['U autobusu sam.', "Ich bin im Bus."], ['Još sam u uredu.', "Ich bin noch im Büro."]] }] },
  'Test 13': { h: 'Zeig, was du kannst', s: 'Wo Menschen und Dinge sind.',
    p2: [{ g: [['grad', 'more', 'škola'], ['u gradu', 'na moru', 'u školi']] }] },

  // ---------- 14 ----------
  'Lesson 14': { h: 'Geschenke machen',
    ex: [['Mami kupujem šal.', "Ich kaufe Mama einen Schal."], ['Pomažem bratu.', "Ich helfe meinem Bruder."]],
    p2: [{ t: [['mama → mami', 'der Mama'], ['tata → tati', 'dem Papa'], ['brat → bratu', 'meinem Bruder']] },
         { w: [['paket', 'package'], ['igračka', 'toy'], ['razglednica', 'postcard']] }] },
  'Vocabulary 14': { h: 'Geben und Empfänger', s: 'Geschenke, Empfänger und Dezemberwörter.',
    p2: [{ w: [['igračka', 'toy'], ['ogrlica', 'necklace'], ['kišobran', 'umbrella']] },
         { w: [['davati', 'give'], ['slati', 'send'], ['donijeti', 'bring']] },
         { w: [['Božić', 'Weihnachten'], ['snijeg', 'snow'], ['poruka', 'message']] }] },
  'Grammar 14': { h: 'Der Dativ',
    ex: [['Baka mi šalje paket.', 'Oma schickt mir ein Paket.'], ['Meni, ne tebi!', 'Mir, nicht dir!']],
    p2: [{ g: [['me', 'you', 'him', 'her'], ['mi', 'ti', 'mu', 'joj']] },
         { w: [['Komu?', 'Wem?']] }] },
  'Practice 14': { h: 'Dezembergeschenke', s: 'Geschenke, ein Briefträger und eine Karte von Oma.',
    p2: [{ t: [['Komu pišeš?', 'Wem schreibst du?'], ['Pišem baki.', "Ich schreibe Oma."], ['Sretan Božić!', 'Frohe Weihnachten!']] }] },
  'Test 14': { h: 'Zeig, was du kannst', s: 'Jemandem etwas geben und irgendwo sein.',
    p2: [{ t: [['Dajem mami cvijeće.', 'Ich gebe Mama Blumen.'], ['Mama je u kuhinji.', 'Mama ist in der Küche.']] }] },

  // ---------- 15 ----------
  'Lesson 15': { h: 'Ausgehen',
    ex: [['Idem s Markom.', "Ich gehe mit Marko."], ['Idemo vlakom.', "Wir fahren mit dem Zug."]],
    p2: [{ t: [['s bratom', 'mit meinem Bruder'], ['sa sestrom', 'mit meiner Schwester'], ['tramvajem', 'mit der Straßenbahn']] },
         { w: [['zabava', 'party'], ['večera', 'dinner'], ['izlazak', 'Abend in der Stadt']] }] },
  'Vocabulary 15': { h: 'Ausgehen und Wetter', s: 'Ein Abend in der Stadt, Verkehrsmittel und das Wetter.',
    p2: [{ w: [['zabava', 'party'], ['večera', 'dinner'], ['ples', 'dance']] },
         { w: [['trajekt', 'ferry'], ['skuter', 'scooter'], ['pješice', 'zu Fuß']] },
         { w: [['kiša', 'rain'], ['vjetar', 'wind'], ['oblak', 'cloud']] }] },
  'Grammar 15': { h: 'Der Instrumental',
    ex: [['Pišem olovkom.', 'Ich schreibe mit einem Bleistift.'], ['Idem s tobom.', "Ich gehe mit dir."]],
    p2: [{ g: [['brat', 'sestra', 'prijatelj'], ['bratom', 'sestrom', 'prijateljem']] },
         { w: [['sa mnom', 'mit mir'], ['s tobom', 'mit dir']] }] },
  'Practice 15': { h: 'Freitagabend', s: 'Ausgehen, eine Zugfahrt und eine Café-Karte.',
    p2: [{ t: [['S kim ideš?', 'Mit wem gehst du?'], ['Sa sestrom.', 'Mit meiner Schwester.'], ['Kava s mlijekom', 'Kaffee mit Milch']] }] },
  'Test 15': { h: 'Zeig, was du kannst', s: 'Vier Fälle, ein Wort.',
    p2: [{ t: [['Vidim mamu.', 'Ich sehe Mama.'], ['Pišem mami.', "Ich schreibe Mama."], ['Pričam o mami.', "Ich rede über Mama."], ['Idem s mamom.', "Ich gehe mit Mama."]] }] },

  // ---------- 16 ----------
  'Lesson 16': { h: "Omas Haus",
    ex: [['Kava bez šećera.', 'Kaffee ohne Zucker.'], ['Nema problema!', 'Kein Problem!']],
    p2: [{ t: [['kod bake', "bei Oma"], ['iz Zagreba', 'aus Zagreb'], ['pokraj kuće', 'neben dem Haus']] },
         { w: [['vrt', 'garden'], ['vrata', 'door'], ['miris', 'smell']] }] },
  'Vocabulary 16': { h: 'Haus und Zuhause', s: 'Wörter fürs Zuhause und kleine Ortswörter.',
    p2: [{ w: [['miris', 'smell'], ['boja', 'colour'], ['slika', 'picture']] },
         { w: [['bez', 'without'], ['iz', 'from'], ['kod', 'at']] },
         { w: [['ispred', 'vor'], ['iza', 'behind'], ['ispod', 'under']] }] },
  'Grammar 16': { h: 'Der Genitiv',
    ex: [['kuća moje bake', "das Haus meiner Oma"], ['Dvije kave, molim.', 'Zwei Kaffee, bitte.']],
    p2: [{ g: [['grad', 'kava', 'noć'], ['grada', 'kave', 'noći']] },
         { w: [['jedna kava', 'ein Kaffee'], ['pet kava', 'fünf Kaffee']] }] },
  'Practice 16': { h: 'Der Weg ans Meer', s: "Omas Haus, ein Café und eine Fahrt an die Küste.",
    p2: [{ t: [['Pokraj kuće je vrt.', 'Neben dem Haus ist ein Garten.'], ['Jedan čaj za Marka.', 'Einen Tee für Marko.'], ['Putujemo iz Zagreba.', "Wir reisen aus Zagreb ab."]] }] },
  'Test 16': { h: 'Zeig, was du kannst', s: 'Der Genitiv und das Zuhause.',
    p2: [{ g: [['grad', 'baka', 'more'], ['iz grada', 'kod bake', 'do mora']] }] },

  // ---------- 17 ----------
  'Lesson 17': { h: 'Befehle geben',
    ex: [['Uzmi tri jaja.', 'Nimm drei Eier.'], ['Skrenite lijevo.', 'Biegen Sie links ab.']],
    p2: [{ t: [['Gledaj!', 'Schau!'], ['Uzmi!', 'Take!'], ['Pij!', 'Trink!']] },
         { w: [['lijevo', 'left'], ['desno', 'right'], ['ravno', 'geradeaus']] }] },
  'Vocabulary 17': { h: 'Rezepte und Wegbeschreibungen', s: 'Küchenwörter, Befehle und Wegbeschreibungen.',
    p2: [{ w: [['brašno', 'flour'], ['tava', 'pan'], ['ulje', 'oil']] },
         { w: [['uzmi', 'take'], ['dodaj', 'add'], ['miješaj', 'mix']] },
         { w: [['lijevo', 'left'], ['desno', 'right'], ['ravno', 'geradeaus']] }] },
  'Grammar 17': { h: 'Der Imperativ',
    ex: [['Gledajte!', 'Schaut! (ihr alle)'], ['Možeš li mi pomoći?', 'Kannst du mir helfen?']],
    p2: [{ g: [['ti', 'vi', "let's"], ['gledaj', 'gledajte', 'gledajmo']] },
         { w: [['mogu', 'ich kann'], ['moram', 'ich muss'], ['hoću', 'ich will']] }] },
  'Practice 17': { h: 'Rezepte und Wegbeschreibungen', s: 'Pfannkuchen, der Weg zum Bahnhof und ein strenger Trainer.',
    p2: [{ t: [['Gdje je kolodvor?', 'Wo ist der Bahnhof?'], ['Idite ravno.', 'Gehen Sie geradeaus.'], ['Pij vodu!', 'Trink Wasser!']] }] },
  'Test 17': { h: 'Zeig, was du kannst', s: 'Befehle, Rezepte und Wegbeschreibungen.',
    p2: [{ g: [['ti', 'vi'], ['gledaj', 'gledajte'], ['uzmi', 'uzmite'], ['pij', 'pijte']] }] },

  // ---------- 18 ----------
  'Lesson 18': { h: 'Eine Million Euro',
    ex: [['Kupio bih kuću.', 'Ich würde ein Haus kaufen.'], ['Htjela bih kavu.', "Ich hätte gern einen Kaffee."]],
    p2: [{ t: [['Kupio bih...', 'Ich würde … kaufen. (er)'], ['Kupila bih...', 'Ich würde … kaufen. (sie)'], ['Biste li mogli...?', 'Könnten Sie …?']] },
         { w: [['san', 'dream'], ['sreća', 'happiness'], ['ako', 'if']] }] },
  'Vocabulary 18': { h: 'Wünsche und Gefühle', s: 'Träume, Gefühle und „würde“.',
    p2: [{ w: [['san', 'dream'], ['jahta', 'yacht'], ['vila', 'villa']] },
         { w: [['sreća', 'happiness'], ['strah', 'fear'], ['nada', 'hope']] },
         { w: [['sanjati', 'dream'], ['nadati se', 'hope'], ['bojati se', 'fear']] }] },
  'Grammar 18': { h: 'Der Konditional',
    ex: [['Išli bismo na more.', 'Wir würden ans Meer fahren.'], ['Ne bih žurila.', "Ich würde mich nicht beeilen."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['bih', 'bi', 'bi'], ['mi', 'vi', 'oni'], ['bismo', 'biste', 'bi']], gh: [0, 2] }] },
  'Practice 18': { h: 'Träume und perfekte Tage', s: 'Lottoträume, ein perfekter Tag und eine Straßenumfrage.',
    p2: [{ t: [['Prvo bih kupio kuću.', "Zuerst würde ich ein Haus kaufen."], ['Svaki dan bih plivala.', "Ich würde jeden Tag schwimmen."], ['Što biste radili?', 'Was würden Sie tun?']] }] },
  'Test 18': { h: 'Zeig, was du kannst', s: 'Wünsche, Träume und Gefühle.',
    p2: [{ g: [['he', 'she'], ['kupio bih', 'kupila bih'], ['htio bih', 'htjela bih']] }] },

  // ---------- 19 ----------
  'Lesson 19': { h: 'Verbzwillinge',
    ex: [['Pisao sam pismo.', 'Ich war dabei, einen Brief zu schreiben.'], ['Napisao sam pismo.', 'Ich habe den Brief fertig geschrieben.']],
    p2: [{ t: [['pisati → napisati', 'schreiben → fertig schreiben'], ['piti → popiti', 'trinken → austrinken'], ['čitati → pročitati', 'lesen → ganz durchlesen']] },
         { w: [['dugo', 'lange'], ['napokon', 'finally'], ['odmah', 'sofort']] }] },
  'Vocabulary 19': { h: 'Geschichten und Ereignisse', s: 'Verbpaare, Zeitwörter und Erzählwörter.',
    p2: [{ t: [['učiti → naučiti', 'lernen → erlernen'], ['kupovati → kupiti', 'einkaufen → kaufen']] },
         { w: [['napokon', 'finally'], ['odjednom', 'suddenly'], ['već', 'already']] }] },
  'Grammar 19': { h: 'Fertig oder nicht?',
    ex: [['Ana je učila cijelu večer.', 'Ana hat den ganzen Abend gelernt.'], ['Naučila je sve.', 'Sie hat alles gelernt.']],
    p2: [{ g: [['im Verlauf', 'finished'], ['pisati', 'napisati'], ['piti', 'popiti'], ['kupovati', 'kupiti']] }] },
  'Practice 19': { h: 'Der Brief', s: 'Ein langer Brief, Hausaufgaben und eine Samstagsliste.',
    p2: [{ t: [['Jesi li napisao zadaću?', 'Hast du deine Hausaufgaben fertig?'], ['Skoro!', 'Fast!'], ['Napokon!', 'Endlich!']] }] },
  'Test 19': { h: 'Zeig, was du kannst', s: 'Verbpaare: im Verlauf oder abgeschlossen.',
    p2: [{ g: [['im Verlauf', 'finished'], ['pisati', 'napisati'], ['čitati', 'pročitati'], ['raditi', 'napraviti']] }] },

  // ---------- 20 ----------
  'Lesson 20': { h: 'Lange Sätze',
    ex: [['Ostajem doma jer pada kiša.', "Ich bleibe zu Hause, weil es regnet."], ['Ako je sunčano, idemo van.', "Wenn es sonnig ist, gehen wir raus."]],
    p2: [{ t: [['jer', 'because'], ['kad', 'when'], ['ako', 'if'], ['iako', 'although']] },
         { w: [['koji', 'der, welcher'], ['da', 'that']] }] },
  'Vocabulary 20': { h: 'Erinnerungen und lange Sätze', s: 'Bindewörter, Sommererinnerungen und Lernen.',
    p2: [{ w: [['jer', 'because'], ['kad', 'when'], ['ako', 'if']] },
         { w: [['dok', 'while'], ['iako', 'although'], ['kao', 'like']] },
         { w: [['uspomena', 'memory'], ['otok', 'island'], ['galeb', 'seagull']] }] },
  'Grammar 20': { h: 'Komplexe Sätze',
    ex: [['Mislim da ćeš doći.', "Ich glaube, dass du kommst."], ['film koji gledam', "der Film, den ich schaue"]],
    p2: [{ t: [['Kad dođeš, zovi me.', 'Wenn du kommst, ruf mich an.'], ['Znam da je velik.', 'Ich weiß, dass es groß ist.']] },
         { w: [['da', 'that'], ['koji', 'der, welcher']] }] },
  'Practice 20': { h: 'Der Sommer, an den ich mich erinnere', s: 'Ein Inselsommer, ein Aufsatz und eine Postkarte.',
    p2: [{ t: [['Pozdrav s otoka!', 'Grüße von der Insel!'], ['Draga bako,', 'Liebe Oma,'], ['Učim hrvatski jer...', "Ich lerne Kroatisch, weil …"]] }] },
  'Test 20': { h: 'Der Abschlusstest', s: 'Alles aus allen 20 Lektionen.',
    p2: [{ t: [['Učim.', "Ich lerne."], ['Učio sam.', 'Ich habe gelernt.'], ['Učit ću.', 'Ich werde lernen.'], ['Učio bih.', 'Ich würde lernen.']] }] }
};
