/* =====================================================================
   Croland mini-igre — banka rečenica (novi sadržaj)
   ---------------------------------------------------------------------
   IZVOR. Ugrađuje se u igre pokretanjem `node ugradi.js`.

   RECENICE  [hr, en, razina 1-5]
   PRAZNINE  [hr s ___, en, točno, krivo1, krivo2, razina]
   DIJALOZI  { id, mjesto, emo, razina, redci:[[tko, hr, en], ...] }
   SAVJETI   [hr, en]  — kratke gramatičke natuknice između razina
   ===================================================================== */

var RECENICE = [

/* ---------- razina 1: "X je Y" ---------- */
['Kuća je velika.','The house is big.',1],
['More je plavo.','The sea is blue.',1],
['Kava je topla.','The coffee is warm.',1],
['Auto je crven.','The car is red.',1],
['Knjiga je nova.','The book is new.',1],
['Grad je star.','The city is old.',1],
['Sunce je žuto.','The sun is yellow.',1],
['Nebo je plavo.','The sky is blue.',1],
['Sladoled je hladan.','The ice cream is cold.',1],
['Juha je vruća.','The soup is hot.',1],
['Pas je malen.','The dog is small.',1],
['Mačka je bijela.','The cat is white.',1],
['Stol je velik.','The table is big.',1],
['Soba je čista.','The room is clean.',1],
['Prozor je otvoren.','The window is open.',1],
['Vrata su zatvorena.','The door is closed.',1],
['Ja sam student.','I am a student.',1],
['Ti si moj prijatelj.','You are my friend.',1],
['On je doktor.','He is a doctor.',1],
['Ona je učiteljica.','She is a teacher.',1],
['Mi smo turisti.','We are tourists.',1],
['Vi ste ljubazni.','You are kind.',1],
['Oni su sretni.','They are happy.',1],
['Ovo je moja kuća.','This is my house.',1],
['To je tvoja knjiga.','That is your book.',1],
['Danas je subota.','Today is Saturday.',1],
['Sutra je nedjelja.','Tomorrow is Sunday.',1],
['Sada je podne.','It is noon now.',1],
['Vrijeme je lijepo.','The weather is nice.',1],
['Kruh je svjež.','The bread is fresh.',1],
['Sir je dobar.','The cheese is good.',1],
['Voda je hladna.','The water is cold.',1],
['Čaj je gorak.','The tea is bitter.',1],
['Torta je slatka.','The cake is sweet.',1],
['Riba je svježa.','The fish is fresh.',1],
['Salata je zelena.','The salad is green.',1],
['Cvijeće je lijepo.','The flowers are beautiful.',1],
['Planina je visoka.','The mountain is high.',1],
['Rijeka je duga.','The river is long.',1],
['Otok je malen.','The island is small.',1],
['Plaža je prazna.','The beach is empty.',1],
['Ulica je tiha.','The street is quiet.',1],
['Trg je pun.','The square is full.',1],
['Muzej je zatvoren.','The museum is closed.',1],
['Trgovina je otvorena.','The shop is open.',1],
['Škola je blizu.','The school is near.',1],
['Hotel je daleko.','The hotel is far.',1],
['Moj brat je visok.','My brother is tall.',1],
['Moja sestra je mlada.','My sister is young.',1],
['Baka je dobra.','Grandma is kind.',1],
['Djed je star.','Grandpa is old.',1],
['Dijete je malo.','The child is small.',1],
['Pas je gladan.','The dog is hungry.',1],
['Mačka je umorna.','The cat is tired.',1],
['Zadaća je teška.','The homework is hard.',1],
['Ispit je lak.','The exam is easy.',1],
['Lekcija je zanimljiva.','The lesson is interesting.',1],
['Film je dosadan.','The film is boring.',1],
['Pjesma je lijepa.','The song is beautiful.',1],
['Grad je velik i lijep.','The city is big and beautiful.',1],
['Auto je brz i skup.','The car is fast and expensive.',1],
['More je toplo i mirno.','The sea is warm and calm.',1],
['Soba je mala, ali čista.','The room is small but clean.',1],
['Kava je jaka i vruća.','The coffee is strong and hot.',1],
['Ja sam umoran.','I am tired.',1],
['Nije loše.','Not bad.',1],
['To je sve.','That is all.',1],
['Ovo je moj grad.','This is my city.',1],

/* ---------- razina 2: prezent, jednostavne rečenice ---------- */
['Ja pijem kavu.','I drink coffee.',2],
['Ti čitaš knjigu.','You read a book.',2],
['On jede kruh.','He eats bread.',2],
['Ona piše pismo.','She writes a letter.',2],
['Mi učimo hrvatski.','We study Croatian.',2],
['Vi gledate film.','You watch a film.',2],
['Oni slušaju glazbu.','They listen to music.',2],
['Ja radim u uredu.','I work in an office.',2],
['Ti živiš u Zagrebu.','You live in Zagreb.',2],
['On putuje u Split.','He travels to Split.',2],
['Ona kuha juhu.','She cooks soup.',2],
['Mi idemo u školu.','We go to school.',2],
['Volim more.','I love the sea.',2],
['Ne volim kišu.','I do not like rain.',2],
['Imam psa.','I have a dog.',2],
['Nemam vremena.','I have no time.',2],
['Znam odgovor.','I know the answer.',2],
['Ne znam gdje je.','I do not know where it is.',2],
['Vidim planinu.','I see a mountain.',2],
['Čekam autobus.','I am waiting for the bus.',2],
['Tražim ključ.','I am looking for the key.',2],
['Kupujem kruh.','I am buying bread.',2],
['Plaćam kavu.','I am paying for the coffee.',2],
['Govorim malo hrvatski.','I speak a little Croatian.',2],
['Razumijem te.','I understand you.',2],
['Pitam učiteljicu.','I am asking the teacher.',2],
['Otvaram prozor.','I am opening the window.',2],
['Zatvaram vrata.','I am closing the door.',2],
['Nosim torbu.','I am carrying a bag.',2],
['Šaljem pismo.','I am sending a letter.',2],
['Zovem prijatelja.','I am calling a friend.',2],
['Gdje je kolodvor?','Where is the train station?',2],
['Kako se zoveš?','What is your name?',2],
['Odakle si?','Where are you from?',2],
['Koliko to košta?','How much does it cost?',2],
['Što radiš danas?','What are you doing today?',2],
['Kada dolazi vlak?','When does the train arrive?',2],
['Zašto čekaš?','Why are you waiting?',2],
['Tko je to?','Who is that?',2],
['Imaš li kartu?','Do you have a ticket?',2],
['Govoriš li engleski?','Do you speak English?',2],
['Želiš li kavu?','Would you like a coffee?',2],
['Idemo na plažu.','We are going to the beach.',2],
['Sjedimo u kafiću.','We are sitting in a café.',2],
['Djeca se igraju u parku.','The children are playing in the park.',2],
['Pas trči po plaži.','The dog runs along the beach.',2],
['Ptica leti visoko.','The bird flies high.',2],
['Sunce sja.','The sun is shining.',2],
['Kiša pada.','It is raining.',2],
['Vjetar puše.','The wind is blowing.',2],
['Snijeg pada u prosincu.','Snow falls in December.',2],
['Vlak kasni.','The train is late.',2],
['Autobus dolazi.','The bus is coming.',2],
['Trgovina se zatvara u osam.','The shop closes at eight.',2],
['Restoran radi do ponoći.','The restaurant is open until midnight.',2],
['Kuham večeru.','I am cooking dinner.',2],
['Perem suđe.','I am washing the dishes.',2],
['Čistim sobu.','I am cleaning the room.',2],
['Učim svaki dan.','I study every day.',2],
['Ustajem rano.','I get up early.',2],
['Spavam do devet.','I sleep until nine.',2],
['Radim od devet do pet.','I work from nine to five.',2],
['Vikendom putujem.','At weekends I travel.',2],
['Petkom gledamo film.','On Fridays we watch a film.',2],
['Ona pjeva u zboru.','She sings in a choir.',2],
['On svira gitaru.','He plays the guitar.',2],
['Marko igra nogomet.','Marko plays football.',2],
['Ana pliva u moru.','Ana swims in the sea.',2],
['Moj tata vozi auto.','My dad drives a car.',2],
['Moja mama kuha ručak.','My mum cooks lunch.',2],
['Baka priča priču.','Grandma tells a story.',2],
['Djed čita novine.','Grandpa reads the newspaper.',2],
['Konobar donosi kavu.','The waiter brings the coffee.',2],
['Poštar nosi pisma.','The postman carries letters.',2],
['Doktor pomaže ljudima.','The doctor helps people.',2],
['Učiteljica objašnjava lekciju.','The teacher explains the lesson.',2],
['Turisti fotografiraju katedralu.','Tourists photograph the cathedral.',2],
['Ne razumijem pitanje.','I do not understand the question.',2],
['Ne mogu doći danas.','I cannot come today.',2],

/* ---------- razina 3: padeži, prijedlozi, usporedba ---------- */
['Idem u grad autobusom.','I am going to town by bus.',3],
['Živim u malom stanu.','I live in a small flat.',3],
['Knjiga je na stolu.','The book is on the table.',3],
['Ključ je u torbi.','The key is in the bag.',3],
['Mačka spava ispod stola.','The cat sleeps under the table.',3],
['Pas je iza kuće.','The dog is behind the house.',3],
['Trgovina je pored pekare.','The shop is next to the bakery.',3],
['Kafić je preko puta muzeja.','The café is across from the museum.',3],
['Idem kod prijatelja.','I am going to a friend’s place.',3],
['Dolazim iz Hrvatske.','I come from Croatia.',3],
['Putujem u Dubrovnik vlakom.','I travel to Dubrovnik by train.',3],
['Vraćam se iz škole.','I am coming back from school.',3],
['Kupujem kruh u pekari.','I buy bread at the bakery.',3],
['Pijem kavu s mlijekom.','I drink coffee with milk.',3],
['Jedem ribu bez soli.','I eat fish without salt.',3],
['Razgovaram s učiteljicom.','I am talking with the teacher.',3],
['Idem na more s obitelji.','I am going to the seaside with my family.',3],
['Sjedim pored prozora.','I am sitting by the window.',3],
['Čekam te ispred kina.','I am waiting for you in front of the cinema.',3],
['Nalazimo se na trgu u pet.','We are meeting on the square at five.',3],
['Nemam novca za kartu.','I do not have money for a ticket.',3],
['Treba mi pomoć.','I need help.',3],
['Sviđa mi se ovaj grad.','I like this city.',3],
['Ne sviđa mi se ta boja.','I do not like that colour.',3],
['Hladno mi je.','I am cold.',3],
['Vruće mi je.','I am hot.',3],
['Drago mi je.','Nice to meet you.',3],
['Žao mi je.','I am sorry.',3],
['Dosadno mi je.','I am bored.',3],
['Ovo je knjiga moje sestre.','This is my sister’s book.',3],
['To je auto našeg susjeda.','That is our neighbour’s car.',3],
['Boja neba je siva.','The colour of the sky is grey.',3],
['Cijena karte je visoka.','The price of the ticket is high.',3],
['Kraj filma je tužan.','The end of the film is sad.',3],
['Dajem knjigu bratu.','I am giving the book to my brother.',3],
['Pišem pismo prijateljici.','I am writing a letter to a friend.',3],
['Pomažem mami u kuhinji.','I am helping mum in the kitchen.',3],
['Šaljem razglednicu baki.','I am sending a postcard to grandma.',3],
['Idem u restoran na večeru.','I am going to the restaurant for dinner.',3],
['Naručujem veliku salatu.','I am ordering a big salad.',3],
['Želim hladno pivo, molim.','I would like a cold beer, please.',3],
['Možemo li dobiti račun?','Can we get the bill?',3],
['Ima li slobodan stol?','Is there a free table?',3],
['Gdje mogu kupiti kartu?','Where can I buy a ticket?',3],
['Kada polazi trajekt?','When does the ferry leave?',3],
['Koliko traje vožnja?','How long does the ride take?',3],
['Je li ovo pravi peron?','Is this the right platform?',3],
['Trebam sobu za tri noći.','I need a room for three nights.',3],
['Doručak je uključen u cijenu.','Breakfast is included in the price.',3],
['Soba ima pogled na more.','The room has a sea view.',3],
['Boli me glava.','I have a headache.',3],
['Osjećam se bolje danas.','I feel better today.',3],
['Trebam lijek iz apoteke.','I need medicine from the pharmacy.',3],
['Nemoj zaboraviti ključ!','Do not forget the key!',3],
['Zatvori prozor, molim te.','Close the window, please.',3],
['Dođi ovamo!','Come here!',3],
['Sjedni i odmori se.','Sit down and rest.',3],
['Govori sporije, molim.','Speak more slowly, please.',3],
['Ponovi to još jednom.','Repeat that once more.',3],
['Idemo zajedno u kino.','Let us go to the cinema together.',3],
['Nazovi me sutra.','Call me tomorrow.',3],
['Čuvaj se!','Take care!',3],
['Sretan put!','Have a good trip!',3],
['Nema problema.','No problem.',3],
['U redu je.','It is all right.',3],
['Možda kasnije.','Maybe later.',3],
['Već sam gotov.','I am already done.',3],
['Imam previše posla.','I have too much work.',3],
['Nemam dovoljno vremena.','I do not have enough time.',3],
['Ovaj tjedan sam jako zauzet.','This week I am very busy.',3],
['Volim raditi ujutro.','I like working in the morning.',3],
['Više volim čaj nego kavu.','I prefer tea to coffee.',3],
['Ovo je bolje od onoga.','This is better than that.',3],
['Zagreb je veći od Splita.','Zagreb is bigger than Split.',3],
['Ljeto je toplije od proljeća.','Summer is warmer than spring.',3],
['Ovo je najbolja kava u gradu.','This is the best coffee in town.',3],
['Danas je hladnije nego jučer.','Today is colder than yesterday.',3],
['Vlak je brži od autobusa.','The train is faster than the bus.',3],
['Slažem se s tobom.','I agree with you.',3],
['Ne slažem se.','I do not agree.',3],

/* ---------- razina 4: prošlo vrijeme, modalni glagoli, futur ---------- */
['Jučer sam bio u Splitu.','Yesterday I was in Split.',4],
['Sinoć smo gledali film.','Last night we watched a film.',4],
['Ana je kupila novu haljinu.','Ana bought a new dress.',4],
['Marko je jeo ćevape.','Marko ate ćevapi.',4],
['Nisam čuo tvoj poziv.','I did not hear your call.',4],
['Jesi li završio zadaću?','Did you finish your homework?',4],
['Gdje si bila jutros?','Where were you this morning?',4],
['Vlak je kasnio dva sata.','The train was two hours late.',4],
['Zaboravio sam ključeve kod kuće.','I forgot the keys at home.',4],
['Izgubila sam putovnicu.','I lost my passport.',4],
['Našli smo lijep mali hotel.','We found a nice little hotel.',4],
['Putovali smo cijeli dan.','We travelled the whole day.',4],
['Stigli smo kasno navečer.','We arrived late in the evening.',4],
['Spavao sam samo četiri sata.','I slept only four hours.',4],
['Ustala sam u šest.','I got up at six.',4],
['Radila je do ponoći.','She worked until midnight.',4],
['Naučili smo puno novih riječi.','We learned a lot of new words.',4],
['Pročitao sam cijelu knjigu.','I read the whole book.',4],
['Nisam razumio pitanje.','I did not understand the question.',4],
['Ispit je bio teži nego što sam mislio.','The exam was harder than I thought.',4],
['Moram ići kući.','I have to go home.',4],
['Moramo požuriti.','We have to hurry.',4],
['Možeš li mi posuditi olovku?','Can you lend me a pencil?',4],
['Ne smiješ pušiti ovdje.','You must not smoke here.',4],
['Trebao bih više spavati.','I should sleep more.',4],
['Htio bih rezervirati stol.','I would like to book a table.',4],
['Željela bih čašu vode.','I would like a glass of water.',4],
['Mogli bismo ići na izlet.','We could go on a trip.',4],
['Znaš li plivati?','Can you swim?',4],
['Ne mogu se sjetiti njegova imena.','I cannot remember his name.',4],
['Sutra idem na more.','Tomorrow I am going to the seaside.',4],
['Idući tjedan putujem u Beč.','Next week I am travelling to Vienna.',4],
['Vidjet ćemo se u petak.','We will see each other on Friday.',4],
['Nazvat ću te večeras.','I will call you tonight.',4],
['Bit će lijepo vrijeme.','The weather will be nice.',4],
['Kupit ću novi telefon.','I will buy a new phone.',4],
['Kad završim posao, idem doma.','When I finish work, I am going home.',4],
['Ako pada kiša, ostajemo doma.','If it rains, we stay home.',4],
['Ako imaš vremena, dođi.','If you have time, come over.',4],
['Kad bih imao novca, putovao bih.','If I had money, I would travel.',4],
['Rekao je da dolazi kasnije.','He said he is coming later.',4],
['Mislim da je to dobra ideja.','I think that is a good idea.',4],
['Nadam se da ćeš doći.','I hope you will come.',4],
['Znam da si umoran.','I know you are tired.',4],
['Bojim se da nemamo vremena.','I am afraid we do not have time.',4],
['Drago mi je što si došao.','I am glad you came.',4],
['Žao mi je što kasnim.','I am sorry I am late.',4],
['Iako je hladno, idemo van.','Although it is cold, we are going out.',4],
['Kupio sam kruh, sir i mlijeko.','I bought bread, cheese and milk.',4],
['Na stolu su bile dvije čaše.','There were two glasses on the table.',4],
['U sobi je bilo previše ljudi.','There were too many people in the room.',4],
['Bilo je jako toplo cijeli tjedan.','It was very hot all week.',4],
['Nikad nisam bio u Dubrovniku.','I have never been to Dubrovnik.',4],
['Već sam tri puta bio u Istri.','I have been to Istria three times already.',4],
['Nitko nije došao na vrijeme.','Nobody came on time.',4],
['Ništa nije bilo otvoreno.','Nothing was open.',4],
['Svi su bili sretni.','Everyone was happy.',4],
['Netko je zvao dok si spavao.','Someone called while you were sleeping.',4],
['Ništa se nije dogodilo.','Nothing happened.',4],
['Sve je bilo u redu.','Everything was fine.',4],
['Trebalo mi je dva sata.','It took me two hours.',4],
['Isplatilo se čekati.','It was worth waiting.',4],

/* ---------- razina 5: složene rečenice i izrazi ---------- */
['Da sam znao da dolaziš, spremio bih ručak.','If I had known you were coming, I would have made lunch.',5],
['Iako je bio umoran, ostao je do kraja.','Although he was tired, he stayed until the end.',5],
['Što više učim, to bolje razumijem.','The more I study, the better I understand.',5],
['Umjesto da se žališ, pokušaj nešto promijeniti.','Instead of complaining, try to change something.',5],
['Prije nego što odeš, zatvori prozore.','Before you leave, close the windows.',5],
['Nakon što smo večerali, prošetali smo obalom.','After we had dinner, we walked along the coast.',5],
['Dok sam čekao vlak, čitao sam novine.','While I was waiting for the train, I read the newspaper.',5],
['Čim stignem, javit ću ti se.','As soon as I arrive, I will let you know.',5],
['Nisam siguran hoće li stići na vrijeme.','I am not sure whether he will arrive on time.',5],
['Pitao me želim li ostati na večeri.','He asked me if I wanted to stay for dinner.',5],
['Rekla mi je da se ne brinem.','She told me not to worry.',5],
['Sve ovisi o vremenu.','It all depends on the weather.',5],
['Ne radi se o novcu, nego o vremenu.','It is not about money, but about time.',5],
['Bez obzira na sve, vrijedilo je.','Despite everything, it was worth it.',5],
['Kad bolje razmislim, imaš pravo.','Now that I think about it, you are right.',5],
['Da budem iskren, nisam očekivao ovo.','To be honest, I did not expect this.',5],
['Koliko ja znam, muzej je danas zatvoren.','As far as I know, the museum is closed today.',5],
['Prema planu, krećemo u osam ujutro.','According to the plan, we leave at eight in the morning.',5],
['Što se mene tiče, možemo krenuti odmah.','As far as I am concerned, we can leave right away.',5],
['Nadam se da se nećeš ljutiti.','I hope you will not be angry.',5],
['Bilo bi lijepo kad bismo se češće viđali.','It would be nice if we saw each other more often.',5],
['Sve više ljudi uči hrvatski.','More and more people are learning Croatian.',5],
['Većina turista dolazi ljeti.','Most tourists come in summer.',5],
['Malo tko zna za ovo mjesto.','Few people know about this place.',5],
['Nitko nije mogao objasniti zašto.','Nobody could explain why.',5],
['Uvijek ima nešto novo za naučiti.','There is always something new to learn.',5],
['Trud se na kraju isplati.','Effort pays off in the end.',5],
['Nikad nije kasno za početak.','It is never too late to start.',5],
['Vrijeme brzo prolazi kad se zabavljaš.','Time flies when you are having fun.',5],
['Bolje ikad nego nikad.','Better late than never.',5],
['Tko rano rani, dvije sreće grabi.','The early bird catches the worm.',5],
['Ponavljanje je majka znanja.','Repetition is the mother of learning.',5],
['Riječ po riječ, jezik se gradi.','Word by word, a language is built.',5],
['Ako te nešto muči, reci mi.','If something is bothering you, tell me.',5],
['Ne mogu vjerovati koliko si napredovao.','I cannot believe how much you have progressed.',5],
['Nakon godinu dana govorio je tečno.','After a year he spoke fluently.',5],
['Bilo mi je drago što sam ih ponovno vidio.','I was glad to see them again.',5],
['Uz malo strpljenja sve je moguće.','With a bit of patience everything is possible.',5],
['Svaki početak je težak.','Every beginning is hard.',5],
['Vježba čini majstora.','Practice makes perfect.',5],
['Pomalo se sve slaže.','Little by little everything falls into place.',5],
['Nije mi jasno kako je to moguće.','It is not clear to me how that is possible.',5],
['Čini mi se da smo se već upoznali.','It seems to me we have already met.',5],
['Ispostavilo se da je bio u pravu.','It turned out he was right.',5],
['Na kraju smo ipak stigli na vrijeme.','In the end we did arrive on time.',5]

];

var PRAZNINE = [

['Kuća je ___.','The house is big.','velika','velik','veliko',1],
['More je ___.','The sea is blue.','plavo','plav','plava',1],
['Auto je ___.','The car is fast.','brz','brza','brzo',1],
['Knjiga je ___.','The book is new.','nova','nov','novo',1],
['Sunce je ___.','The sun is warm.','toplo','topao','topla',1],
['Kava je ___.','The coffee is good.','dobra','dobar','dobro',1],
['Nebo je ___.','The sky is grey.','sivo','siv','siva',1],
['Grad je ___.','The city is old.','star','stara','staro',1],
['Soba je ___.','The room is clean.','čista','čist','čisto',1],
['Vino je ___.','The wine is cold.','hladno','hladan','hladna',1],
['Ja ___ student.','I am a student.','sam','si','je',1],
['Ti ___ moj prijatelj.','You are my friend.','si','sam','su',1],
['Oni ___ sretni.','They are happy.','su','smo','ste',1],
['Mi ___ turisti.','We are tourists.','smo','ste','su',1],
['Ona ___ učiteljica.','She is a teacher.','je','su','si',1],
['Vi ___ ljubazni.','You are kind.','ste','si','smo',1],
['Ovo ___ moja kuća.','This is my house.','je','su','sam',1],
['Vrata ___ zatvorena.','The door is closed.','su','je','sam',1],

['Ja ___ kavu.','I drink coffee.','pijem','piješ','pije',2],
['Ti ___ knjigu.','You read a book.','čitaš','čitam','čita',2],
['On ___ kruh.','He eats bread.','jede','jedem','jedu',2],
['Mi ___ hrvatski.','We study Croatian.','učimo','učite','uče',2],
['Oni ___ glazbu.','They listen to music.','slušaju','slušamo','slušate',2],
['Vi ___ film.','You watch a film.','gledate','gledaju','gledamo',2],
['Ona ___ pismo.','She writes a letter.','piše','pišem','pišu',2],
['Ja ___ u uredu.','I work in an office.','radim','radiš','radi',2],
['Ti ___ u Zagrebu.','You live in Zagreb.','živiš','živim','živi',2],
['Mi ___ u školu.','We go to school.','idemo','idete','idu',2],
['Ona ___ juhu.','She cooks soup.','kuha','kuham','kuhaju',2],
['Oni ___ nogomet.','They play football.','igraju','igra','igramo',2],
['Idem ___ školu.','I am going to school.','u','na','iz',2],
['Knjiga je ___ stolu.','The book is on the table.','na','u','iz',2],
['Ključ je ___ torbi.','The key is in the bag.','u','na','pod',2],
['Dolazim ___ Hrvatske.','I come from Croatia.','iz','u','na',2],
['Idem ___ more.','I am going to the seaside.','na','u','iz',2],
['Pijem kavu ___ mlijekom.','I drink coffee with milk.','s','od','za',2],
['Jedem ribu ___ soli.','I eat fish without salt.','bez','s','na',2],
['Vlak dolazi ___ pet sati.','The train arrives at five.','u','na','od',2],

['Čekam te ___ kina.','I am waiting for you in front of the cinema.','ispred','iznad','kroz',3],
['Mačka spava ___ stola.','The cat sleeps under the table.','ispod','iznad','preko',3],
['Trgovina je ___ pekare.','The shop is next to the bakery.','pored','kroz','bez',3],
['Naručujem ___ salatu.','I am ordering a big salad.','veliku','velika','veliki',3],
['Vidim ___ planinu.','I see a high mountain.','visoku','visoka','visok',3],
['Kupujem ___ kruh.','I am buying fresh bread.','svjež','svježa','svježe',3],
['Želim ___ pivo.','I want a cold beer.','hladno','hladan','hladna',3],
['Pijem ___ kavu.','I am drinking hot coffee.','vruću','vruća','vruć',3],
['Nosim ___ torbu.','I am carrying a new bag.','novu','nova','nov',3],
['Dajem knjigu ___.','I am giving the book to my brother.','bratu','brat','brata',3],
['Pišem pismo ___.','I am writing a letter to a friend.','prijateljici','prijateljica','prijateljicu',3],
['Pomažem ___ u kuhinji.','I am helping mum in the kitchen.','mami','mama','mamu',3],
['Šaljem razglednicu ___.','I am sending a postcard to grandma.','baki','baka','baku',3],
['Ovo je knjiga moje ___.','This is my sister’s book.','sestre','sestra','sestru',3],
['To je auto našeg ___.','That is our neighbour’s car.','susjeda','susjed','susjedu',3],
['Cijena ___ je visoka.','The price of the ticket is high.','karte','karta','kartu',3],
['Hladno ___ je.','I am cold.','mi','me','ja',3],
['Sviđa ___ se ovaj grad.','I like this city.','mi','me','ja',3],
['Boli ___ glava.','I have a headache.','me','mi','ja',3],
['Žao ___ je.','I am sorry.','mi','me','ja',3],
['Nemam ___.','I have no time.','vremena','vrijeme','vremenu',3],
['Nemam ___ za kartu.','I have no money for a ticket.','novca','novac','novcu',3],
['U sobi su ___ čaše.','There are two glasses in the room.','dvije','dva','dvoje',3],
['Na stolu je ___ knjiga.','There are five books on the table.','pet','petero','peti',3],
['Više volim čaj ___ kavu.','I prefer tea to coffee.','nego','od','kao',3],
['___ li mi pomoći?','Can you help me?','Možeš','Mogu','Može',3],
['Idem ___ prijatelja.','I am going to a friend’s place.','kod','na','iz',3],
['Putujem u Split ___.','I travel to Split by train.','vlakom','vlak','vlaka',3],
['Razgovaram ___ učiteljicom.','I am talking with the teacher.','s','od','za',3],
['Vraćam se ___ škole.','I am coming back from school.','iz','u','na',3],

['Jučer sam ___ u Splitu.','Yesterday I was in Split.','bio','bila','bilo',4],
['Ana je ___ novu haljinu.','Ana bought a new dress.','kupila','kupio','kupilo',4],
['Sinoć smo ___ film.','Last night we watched a film.','gledali','gledala','gledao',4],
['Nisam ___ tvoj poziv.','I did not hear your call.','čuo','čula','čuli',4],
['Vlak je ___ dva sata.','The train was two hours late.','kasnio','kasnila','kasnili',4],
['Djeca su se ___ u parku.','The children played in the park.','igrala','igrao','igrale',4],
['Sutra ___ te nazvati.','I will call you tomorrow.','ću','ćeš','će',4],
['Vidjet ___ se u petak.','We will see each other on Friday.','ćemo','ćete','će',4],
['Bit ___ lijepo vrijeme.','The weather will be nice.','će','ću','ćeš',4],
['___ ići kući.','I have to go home.','Moram','Moraš','Mora',4],
['Ne ___ pušiti ovdje.','You must not smoke here.','smiješ','smijem','smije',4],
['___ bih rezervirati stol.','I would like to book a table.','Htio','Htjeti','Hoću',4],
['Trebao ___ više spavati.','I should sleep more.','bih','bi','bismo',4],
['Ako ___ kiša, ostajemo doma.','If it rains, we stay home.','pada','padne','padao',4],
['Mislim ___ je to dobra ideja.','I think that is a good idea.','da','koji','ako',4],
['Nadam se ___ ćeš doći.','I hope you will come.','da','što','koji',4],
['Ovo je ___ kava u gradu.','This is the best coffee in town.','najbolja','bolja','dobra',4],
['Zagreb je ___ od Splita.','Zagreb is bigger than Split.','veći','velik','najveći',4],
['Danas je ___ nego jučer.','Today is colder than yesterday.','hladnije','hladno','najhladnije',4],
['Nikad ___ bio u Dubrovniku.','I have never been to Dubrovnik.','nisam','sam','nije',4],
['Nitko ___ došao na vrijeme.','Nobody came on time.','nije','je','nisu',4],
['Ništa se ___ dogodilo.','Nothing happened.','nije','je','nisu',4],
['Trebam sobu za tri ___.','I need a room for three nights.','noći','noć','noćima',4],
['Rezervirao sam stol za ___.','I booked a table for two.','dvoje','dva','dvije',4],

['Čovjek ___ sjedi tamo je moj susjed.','The man sitting there is my neighbour.','koji','koja','koje',5],
['Knjiga ___ čitam je odlična.','The book I am reading is excellent.','koju','koji','koje',5],
['Grad u ___ živim je malen.','The city I live in is small.','kojem','koji','koju',5],
['Prijateljica s ___ putujem govori talijanski.','The friend I travel with speaks Italian.','kojom','koja','koju',5],
['Prije ___ odeš, zatvori prozore.','Before you leave, close the windows.','nego što','kad','dok',5],
['___ sam čekao vlak, čitao sam novine.','While I was waiting for the train, I read the newspaper.','Dok','Čim','Ako',5],
['Čim ___, javit ću ti se.','As soon as I arrive, I will let you know.','stignem','stižem','stigao',5],
['Da sam ___, spremio bih ručak.','If I had known, I would have made lunch.','znao','znam','znati',5],
['Što više učim, ___ bolje razumijem.','The more I study, the better I understand.','to','tako','onda',5],
['Umjesto ___ se žališ, pokušaj nešto promijeniti.','Instead of complaining, try to change something.','da','što','kako',5],
['Nisam siguran ___ li stići na vrijeme.','I am not sure whether he will arrive on time.','hoće','će','bi',5],
['Pitao me ___ li ostati na večeri.','He asked me if I wanted to stay for dinner.','želim','želiš','želi',5],
['Bez ___ na sve, vrijedilo je.','Despite everything, it was worth it.','obzira','obzir','obziru',5],
['Sve ___ o vremenu.','It all depends on the weather.','ovisi','ovise','ovisim',5],
['Ne radi se o novcu, ___ o vremenu.','It is not about money, but about time.','nego','ali','ili',5]

];

var DIJALOZI = [

{ id:'kafic', mjesto:'Kafić', emo:'☕', razina:2, redci:[
  ['npc','Dobar dan! Izvolite?','Good afternoon! What would you like?'],
  ['ti','Dobar dan. Jednu veliku kavu, molim.','Good afternoon. One large coffee, please.'],
  ['npc','S mlijekom ili bez?','With milk or without?'],
  ['ti','S mlijekom, hvala.','With milk, thank you.'],
  ['npc','Odmah stiže. Želite li nešto slatko?','Coming right up. Would you like something sweet?'],
  ['ti','Može jedan kolač.','A pastry would be nice.'],
  ['npc','Izvolite. Ugodan dan!','Here you are. Have a nice day!']
]},

{ id:'pekara', mjesto:'Pekara', emo:'🥖', razina:2, redci:[
  ['npc','Dobro jutro! Što će biti?','Good morning! What will it be?'],
  ['ti','Dobro jutro. Trebam kruh i dva peciva.','Good morning. I need bread and two rolls.'],
  ['npc','Bijeli ili crni kruh?','White or brown bread?'],
  ['ti','Crni, molim. Je li svjež?','Brown, please. Is it fresh?'],
  ['npc','Jutros pečen. Još nešto?','Baked this morning. Anything else?'],
  ['ti','To je sve. Koliko košta?','That is all. How much is it?'],
  ['npc','Četiri eura, molim.','Four euros, please.']
]},

{ id:'trznica', mjesto:'Tržnica', emo:'🏪', razina:3, redci:[
  ['npc','Izvolite, gospodine! Rajčice su danas odlične.','Here you go, sir! The tomatoes are excellent today.'],
  ['ti','Koliko košta kilogram?','How much is a kilogram?'],
  ['npc','Dva eura. Domaće su, iz mog vrta.','Two euros. They are home-grown, from my garden.'],
  ['ti','Uzet ću kilogram rajčica i pola kile paprika.','I will take a kilo of tomatoes and half a kilo of peppers.'],
  ['npc','Odmah. Trebate li još povrća?','Right away. Do you need any more vegetables?'],
  ['ti','Ne, hvala. To je dovoljno za danas.','No, thank you. That is enough for today.'],
  ['npc','Hvala vam i doviđenja!','Thank you and goodbye!']
]},

{ id:'kolodvor', mjesto:'Kolodvor', emo:'🚉', razina:3, redci:[
  ['npc','Dobar dan, kamo putujete?','Good afternoon, where are you travelling?'],
  ['ti','U Split. Kada polazi sljedeći vlak?','To Split. When does the next train leave?'],
  ['npc','U petnaest i trideset, s perona četiri.','At half past three, from platform four.'],
  ['ti','Koliko traje vožnja?','How long does the ride take?'],
  ['npc','Otprilike šest sati.','About six hours.'],
  ['ti','Onda jednu kartu u jednom smjeru, molim.','Then one one-way ticket, please.'],
  ['npc','Izvolite kartu. Sretan put!','Here is your ticket. Have a good trip!']
]},

{ id:'hotel', mjesto:'Hotel', emo:'🏨', razina:3, redci:[
  ['npc','Dobra večer, imate li rezervaciju?','Good evening, do you have a reservation?'],
  ['ti','Da, na ime Marić. Soba za dvije noći.','Yes, under the name Marić. A room for two nights.'],
  ['npc','Našao sam. Soba dvjesto sedam, na drugom katu.','Found it. Room two hundred and seven, on the second floor.'],
  ['ti','Je li doručak uključen u cijenu?','Is breakfast included in the price?'],
  ['npc','Jest, od sedam do deset ujutro.','Yes, from seven to ten in the morning.'],
  ['ti','Odlično. Ima li soba pogled na more?','Excellent. Does the room have a sea view?'],
  ['npc','Ima. Evo vašeg ključa, ugodan boravak!','It does. Here is your key, enjoy your stay!']
]},

{ id:'restoran', mjesto:'Restoran', emo:'🍽', razina:3, redci:[
  ['npc','Dobra večer! Stol za koliko osoba?','Good evening! A table for how many?'],
  ['ti','Za dvoje, molim. Pored prozora ako može.','For two, please. By the window if possible.'],
  ['npc','Naravno. Evo jelovnika.','Of course. Here is the menu.'],
  ['ti','Što preporučujete?','What do you recommend?'],
  ['npc','Svježa riba je danas izvrsna.','The fresh fish is excellent today.'],
  ['ti','Uzet ćemo ribu i veliku salatu.','We will take the fish and a big salad.'],
  ['npc','Odličan izbor. Za piće?','Excellent choice. And to drink?'],
  ['ti','Jednu bocu vode i čašu bijelog vina.','A bottle of water and a glass of white wine.']
]},

{ id:'apoteka', mjesto:'Apoteka', emo:'💊', razina:4, redci:[
  ['npc','Dobar dan, kako vam mogu pomoći?','Good afternoon, how can I help you?'],
  ['ti','Boli me grlo već tri dana.','My throat has hurt for three days.'],
  ['npc','Imate li i temperaturu?','Do you also have a fever?'],
  ['ti','Jučer sam imao, danas mi je bolje.','I had one yesterday, today I feel better.'],
  ['npc','Onda probajte ove pastile. Tri puta na dan.','Then try these lozenges. Three times a day.'],
  ['ti','Trebam li recept?','Do I need a prescription?'],
  ['npc','Ne trebate. Ako se ne popravi, idite liječniku.','You do not. If it does not improve, see a doctor.']
]},

{ id:'susjed', mjesto:'Kod susjeda', emo:'🏘', razina:4, redci:[
  ['npc','Bok! Dugo se nismo vidjeli.','Hi! We have not seen each other for a long time.'],
  ['ti','Bok! Bio sam mjesec dana u Italiji.','Hi! I was in Italy for a month.'],
  ['npc','Sjajno! Kako je bilo?','Great! How was it?'],
  ['ti','Odlično, iako je bilo jako vruće.','Excellent, although it was very hot.'],
  ['npc','A hrana? Jesi li jeo dobro?','And the food? Did you eat well?'],
  ['ti','Previše dobro — vratio sam se pet kila teži!','Too well — I came back five kilos heavier!'],
  ['npc','Ha-ha! Onda idemo trčati sutra ujutro.','Ha-ha! Then let us go running tomorrow morning.']
]},

{ id:'ured', mjesto:'Ured', emo:'🏢', razina:4, redci:[
  ['npc','Dobro jutro, jeste li dobili moju poruku?','Good morning, did you get my message?'],
  ['ti','Jesam, ali nisam stigao odgovoriti.','I did, but I did not get around to replying.'],
  ['npc','Nema problema. Možemo li se naći u dva?','No problem. Can we meet at two?'],
  ['ti','U dva imam drugi sastanak. Može li u tri?','At two I have another meeting. Could we do three?'],
  ['npc','Može. Trebam li nešto pripremiti?','That works. Should I prepare anything?'],
  ['ti','Samo brojke za ovaj mjesec.','Just the figures for this month.'],
  ['npc','U redu, vidimo se u tri.','All right, see you at three.']
]},

{ id:'skola', mjesto:'Škola', emo:'🏫', razina:5, redci:[
  ['npc','Kako napreduje tvoj hrvatski?','How is your Croatian coming along?'],
  ['ti','Bolje nego što sam očekivao, ali padeži su mi teški.','Better than I expected, but the cases are hard for me.'],
  ['npc','Svima su na početku. Čitaš li nešto na hrvatskom?','They are for everyone at the start. Do you read anything in Croatian?'],
  ['ti','Čitam kratke priče i gledam vijesti s titlovima.','I read short stories and watch the news with subtitles.'],
  ['npc','To je najbolji način. Što više slušaš, to prije progovoriš.','That is the best way. The more you listen, the sooner you will speak.'],
  ['ti','Nadam se da ću do ljeta govoriti bez razmišljanja.','I hope that by summer I will speak without thinking.'],
  ['npc','Hoćeš, samo nastavi. Vježba čini majstora.','You will, just keep going. Practice makes perfect.']
]},

{ id:'plaza', mjesto:'Plaža', emo:'🏖', razina:5, redci:[
  ['npc','Je li ovo mjesto slobodno?','Is this spot free?'],
  ['ti','Jest, slobodno sjednite.','It is, please sit down.'],
  ['npc','Hvala. Prekrasan dan, zar ne?','Thank you. A beautiful day, is it not?'],
  ['ti','Predivan. More je toplije nego prošli tjedan.','Wonderful. The sea is warmer than last week.'],
  ['npc','Dolazite li često ovamo?','Do you come here often?'],
  ['ti','Kad god imam slobodan dan. Ovdje se najbolje odmorim.','Whenever I have a day off. This is where I rest best.'],
  ['npc','Razumijem vas. Nakon mora čovjek je novi.','I understand. After the sea one feels like a new person.']
]},

{ id:'tvrdjava', mjesto:'Tvrđava', emo:'🏰', razina:5, redci:[
  ['npc','Dobro došao, putniče. Tražiš li nešto?','Welcome, traveller. Are you looking for something?'],
  ['ti','Tražim ključ koji otvara istočna vrata.','I am looking for the key that opens the eastern gate.'],
  ['npc','Taj ključ čuva onaj tko zna tri riječi.','That key is kept by the one who knows three words.'],
  ['ti','Reci mi koje su, pa ću ih naučiti.','Tell me which ones and I will learn them.'],
  ['npc','Strpljenje, hrabrost i znanje. Sve ostalo dolazi samo.','Patience, courage and knowledge. Everything else comes on its own.'],
  ['ti','Onda mi treba još malo vremena.','Then I need a little more time.'],
  ['npc','Vrijeme imaš. Vrata te čekaju.','You have time. The gate is waiting for you.']
]}

];

var SAVJETI = [
  ['Hrvatski nema članova — „kuća" znači i „a house" i „the house".','Croatian has no articles.'],
  ['Pridjev se slaže s imenicom: velik grad, velika kuća, veliko more.','Adjectives agree with the noun.'],
  ['Muški rod najčešće završava na suglasnik, ženski na -a, srednji na -o ili -e.','Gender endings.'],
  ['U akuzativu ženski rod mijenja -a u -u: salata → salatu.','Accusative of feminine nouns.'],
  ['Neživo u muškom rodu ostaje isto u akuzativu: vidim stol.','Inanimate masculine stays the same.'],
  ['Živo u muškom rodu dobiva -a: vidim psa, vidim brata.','Animate masculine takes -a.'],
  ['Nakon „u" i „na" s mirovanjem ide lokativ: u kući, na stolu.','Locative after u/na for location.'],
  ['S kretanjem „u" i „na" traže akuzativ: idem u školu, idem na more.','Accusative after u/na for motion.'],
  ['„Bez", „iz", „od", „do" uvijek traže genitiv.','These prepositions take the genitive.'],
  ['Negacija: ne + glagol, ali „nemam" i „neću" pišu se spojeno.','Negation is written together in some verbs.'],
  ['Pitanje se često tvori s „li": Imaš li vremena?','Questions with li.'],
  ['Prošlo vrijeme: pomoćni glagol + glagolski pridjev (bio sam, kupila je).','Past tense formation.'],
  ['Glagolski pridjev se slaže s rodom: on je bio, ona je bila, oni su bili.','Past participle agrees in gender.'],
  ['Futur: infinitiv + ću/ćeš/će (kupit ću, doći ćemo).','Future tense formation.'],
  ['Dativ odgovara na pitanje „kome": dajem knjigu bratu.','Dative answers "to whom".'],
  ['„Sviđa mi se" doslovno znači „it is pleasing to me".','Liking is expressed with the dative.'],
  ['Komparativ: velik → veći, dobar → bolji, hladan → hladniji.','Comparative forms.'],
  ['Superlativ se tvori s naj-: najveći, najbolji, najhladniji.','Superlative with naj-.'],
  ['Instrumental za sredstvo: putujem vlakom, pišem olovkom.','Instrumental for means.'],
  ['Uz brojeve 2, 3 i 4 imenica ide u genitiv jednine: dva stola.','Numbers 2-4 take genitive singular.'],
  ['Od pet nadalje ide genitiv množine: pet stolova.','Numbers 5+ take genitive plural.'],
  ['Dvostruka negacija je normalna: nitko ništa ne zna.','Double negation is standard.'],
  ['Red riječi je slobodan, ali enklitike (je, sam, se) idu na drugo mjesto.','Clitics go in second position.'],
  ['„Se" se piše odvojeno i mijenja mjesto: odmori se, ja se odmaram.','Reflexive se placement.'],
  ['Slova dž, lj i nj su jedno slovo, ne dva.','Digraphs are single letters.'],
  ['Č je tvrđe, ć je mekše — čokolada, ćevapi.','Č vs ć.'],
  ['Svako slovo se uvijek čita isto — hrvatski je fonetski jezik.','Croatian is phonetic.'],
  ['Naglasak je najčešće na prvom slogu, nikad na zadnjem.','Stress is never on the last syllable.'],
  ['Vokativ se koristi za dozivanje: Marko → Marko!, Ana → Ana!','Vocative for addressing.'],
  ['„Vi" iz poštovanja piše se velikim slovom u pismima.','Formal Vi is capitalised in letters.']
];

/* parovi suprotnica — [riječ, suprotnica, en] */
var SUPROTNICE = [
  ['velik','mali','big / small'],
  ['nov','star','new / old'],
  ['dobar','loš','good / bad'],
  ['lijep','ružan','beautiful / ugly'],
  ['topao','hladan','warm / cold'],
  ['brz','spor','fast / slow'],
  ['skup','jeftin','expensive / cheap'],
  ['visok','nizak','tall / low'],
  ['dug','kratak','long / short'],
  ['težak','lagan','heavy / light'],
  ['pun','prazan','full / empty'],
  ['čist','prljav','clean / dirty'],
  ['mokar','suh','wet / dry'],
  ['glasan','tih','loud / quiet'],
  ['svijetao','taman','bright / dark'],
  ['mek','tvrd','soft / hard'],
  ['bogat','siromašan','rich / poor'],
  ['sretan','tužan','happy / sad'],
  ['miran','ljut','calm / angry'],
  ['zauzet','slobodan','busy / free'],
  ['širok','uzak','wide / narrow'],
  ['debeo','tanak','thick / thin'],
  ['sladak','gorak','sweet / bitter'],
  ['zdrav','bolestan','healthy / ill'],
  ['siguran','opasan','safe / dangerous'],
  ['zanimljiv','dosadan','interesting / boring'],
  ['rano','kasno','early / late'],
  ['brzo','polako','quickly / slowly'],
  ['ovdje','tamo','here / there'],
  ['gore','dolje','up / down'],
  ['lijevo','desno','left / right'],
  ['blizu','daleko','near / far'],
  ['uvijek','nikad','always / never'],
  ['puno','malo','a lot / a little'],
  ['danas','sutra','today / tomorrow'],
  ['otvoriti','zatvoriti','to open / to close'],
  ['doći','otići','to come / to leave'],
  ['početi','završiti','to start / to finish'],
  ['kupovati','prodati','to buy / to sell'],
  ['uzeti','dati','to take / to give'],
  ['naći','izgubiti','to find / to lose'],
  ['smijati se','plakati','to laugh / to cry'],
  ['govoriti','šutjeti','to speak / to be silent'],
  ['zapamtiti','zaboraviti','to memorise / to forget'],
  ['ustati','spavati','to get up / to sleep'],
  ['pitati','odgovoriti','to ask / to answer'],
  ['jutro','večer','morning / evening'],
  ['dan','noć','day / night'],
  ['ljeto','zima','summer / winter'],
  ['pobjeda','poraz','victory / defeat'],
  ['sreća','tuga','happiness / sadness'],
  ['ljubav','strah','love / fear'],
  ['pitanje','odgovor','question / answer'],
  ['polazak','dolazak','departure / arrival'],
  ['crn','bijel','black / white']
];

if (typeof module !== 'undefined') module.exports = {
  RECENICE: RECENICE, PRAZNINE: PRAZNINE, DIJALOZI: DIJALOZI,
  SAVJETI: SAVJETI, SUPROTNICE: SUPROTNICE
};
